### ISSUE TITLE
kUbuntu 22.04 wine Crash

### ISSUE THREAD

**Issue by Donno191** [VoidXH/Cavern#1]
When i run in kUbuntu 22.04 everything runs fine for about 6sec to 15sec then crashes with output -> Segmentation fault (core dumped)

Terminal EXE -> ~/Downloads/cavern64$ wine Cavern.exe
[UnityMemory] Configuration Parameters - Can be set up in boot.config
    "memorysetup-bucket-allocator-granularity=16"
    "memorysetup-bucket-allocator-bucket-count=8"
    "memorysetup-bucket-allocator-block-size=4194304"
    "memorysetup-bucket-allocator-block-count=1"
    "memorysetup-main-allocator-block-size=16777216"
    "memorysetup-thread-allocator-block-size=16777216"
    "memorysetup-gfx-main-allocator-block-size=16777216"
    "memorysetup-gfx-thread-allocator-block-size=16777216"
    "memorysetup-cache-allocator-block-size=4194304"
    "memorysetup-typetree-allocator-block-size=2097152"
    "memorysetup-profiler-bucket-allocator-granularity=16"
    "memorysetup-profiler-bucket-allocator-bucket-count=8"
    "memorysetup-profiler-bucket-allocator-block-size=4194304"
    "memorysetup-profiler-bucket-allocator-block-count=1"
    "memorysetup-profiler-allocator-block-size=16777216"
    "memorysetup-profiler-editor-allocator-block-size=1048576"
    "memorysetup-temp-allocator-size-main=4194304"
    "memorysetup-job-temp-allocator-block-size=2097152"
    "memorysetup-job-temp-allocator-block-size-background=1048576"
    "memorysetup-job-temp-allocator-reduction-small-platforms=262144"
    "memorysetup-temp-allocator-size-background-worker=32768"
    "memorysetup-temp-allocator-size-job-worker=262144"
    "memorysetup-temp-allocator-size-preload-manager=262144"
    "memorysetup-temp-allocator-size-nav-mesh-worker=65536"
    "memorysetup-temp-allocator-size-audio-worker=65536"
    "memorysetup-temp-allocator-size-cloud-worker=32768"
    "memorysetup-temp-allocator-size-gfx=262144"
Mono path[0] = 'Z:/home/donno/Downloads/cavern64/Cavern_Data/Managed'
Mono config path = 'Z:/home/donno/Downloads/cavern64/MonoBleedingEdge/etc'
Initialize engine version: 2021.2.5f1 (4ec9a5e799f5)
[Subsystems] Discovering subsystems at path Z:/home/donno/Downloads/cavern64/Cavern_Data/UnitySubsystems
GfxDevice: creating device client; threaded=1; jobified=0
Direct3D:
    Version:  Direct3D 11.0 [level 11.1]
    Renderer: Radeon (TM) RX 480 Graphics (ID=0x67df)
    Vendor:   ATI
    VRAM:     4096 MB
    Driver:   1.0
Begin MonoManager ReloadAssembly
- Completed reload, in  0.184 seconds
<RI> Initializing input.
<RI> Input initialized.
<RI> Touch support initialization failed: Call not implemented.
.
UnloadTime: 0.817600 ms
Setting up 4 worker threads for Enlighten.
Segmentation fault (core dumped)

**Comment by Donno191** [comment]
PS: i ran the 64-bit exe file from website

**Comment by VoidXH** [comment]
Hi, I see your ticket is 4 days old. A major update was released 2 days ago, please try with that one.

**Comment by Donno191** [comment]
Hi, just tested it and it seems to work fine. Thank You
