### ISSUE TITLE
The DRC  in eac3 is applied always when decode

### ISSUE THREAD

**Issue by tebasuna51** [VoidXH/Cavern#10]
And the output have less volume than source.

When decode must use -drc_scale 0 like ffmpeg (not allowed here)

**Comment by ValZapod** [comment]
Yes, of course. Totally forgot to report that. I will note though that DRC in EAE.exe is so much more powerful.

**Comment by VoidXH** [comment]
Will add this to the decode arguments.

**Comment by VoidXH** [comment]
Fixed in ec56bee1f54a6a53e5659da834863a9ff769da62.

**Comment by ValZapod** [comment]
It still does not aapply for ADM, only for pcm. :)

**Comment by VoidXH** [comment]
Added as a task to #8.

**Comment by VoidXH** [comment]
Fixed in 6317705909607eb0e0f670f8ed35b4688d93b4a6.
