### ISSUE TITLE
How does Cavern play multi-channel audio in Unity3d

### ISSUE THREAD

**Issue by WangEdgar** [VoidXH/Cavern#103]
When importing 12-channel audio in Unity3d, error will be reported when playing through AudioSource3D. Do you need some kind of setup?

**Comment by VoidXH** [comment]
You have to use Cavern's own classes for Atmos, AudioSource3D only works up to 7.1 (same as Unity's AudioSource). Tracks are decoded with AudioReaders, they have Renderers, and the Renderers have Sources, which can be mapped into Unity with a Follower.
