### ISSUE TITLE
17 total objects; bug as in Trinnov, does not happen with report

### ISSUE THREAD

**Issue by ValZapod** [VoidXH/Cavern#11]
![image](https://user-images.githubusercontent.com/31514790/189548928-3acafbed-6175-4cc0-aa9c-29e156cfbb97.png)

00003.m2ts sample from here: https://drive.google.com/drive/folders/1E4Go5zLiR4LlMiT8GQTJxxF22-4q1qTe?usp=sharing

Trinnov has same bug sometimes (on Mulan): https://youtu.be/CBqWYrOMxcY?t=503

**Comment by VoidXH** [comment]
Fixed in 816f7c28703605692d13eb9c56ae26a2d30b37a3.

**Comment by ValZapod** [comment]
Fixed, though report now says 14 objects and two beds, while Export says it is 15 objects and 1 bed. Who is right?

**Comment by VoidXH** [comment]
The report. It will classify objects that don't move a channel.
