### ISSUE TITLE
"Open audio file" at the top-right is not displayed

### ISSUE THREAD

**Issue by eviluess** [VoidXH/Cavern#110]
I downloaded Cavern Driver 1.6 from https://cavern.sbence.hu/cavern/downloads.php and ran it.
But I can't see the "Open audio file" button at the top-right of the interface.

**Comment by VoidXH** [comment]
Use the bottom option when the application is launched.

**Comment by VoidXH** [comment]
I'll just reopen this because the documentation needs to be updated for the new layout.

**Comment by VoidXH** [comment]
Documentation updated.
