### ISSUE TITLE
Option to Hide Sofa, Speakers, Screen and Measurement Guide?

### ISSUE THREAD

**Issue by hockinsk** [VoidXH/Cavern#111]
Really enjoy exploring dd+joc music with Cavern and learning about what is happening with the objects/spatial groupings. Would it be possible to add a feature to hide the Speakers, Screen and Measurements and perhaps replace the Sofa with a persons head (similar to spatial audio rooms / 3D panners)?

**Comment by VoidXH** [comment]
Yes. While a head is not possible without a modeler and with the strict no asset policy, a transparent wall replacement for the room size and toggling the environment models is.

**Comment by hockinsk** [comment]
OK, great stuff, thank you for all the work on this application!

**Comment by VoidXH** [comment]
Done and released.

**Comment by hockinsk** [comment]
Awesome, thank you!
