### ISSUE TITLE
Creating dynamic channels with movement using Cavern API

### ISSUE THREAD

**Issue by EnriqueSampaio** [VoidXH/Cavern#113]
First of all, congratulations on the project, what a great tool!

I'm trying to use Cavern to generate some ADMs programmatically, and I've been able to successfully map sources to beds and export valid Dolby Atmos masters. I also managed to create some objects associated with the listener, my difficulty is in giving movement to those objects. Could you give me a north of which Cavern API tools can help me with this? Or say if it is not possible and I will have to look for another library to help with that task? Remembering that I'm using the Cavern project to do this programmatically.

Thank you in advance, and again, congrats on this powerful project!

**Comment by VoidXH** [comment]
The general example for this is CavernizeGUI. You will need to export frame by frame, and move the Sources around in those times. I've just made you an example code in 30767fcb1337e60bf888d4a052837fe0959f2be6.

**Comment by EnriqueSampaio** [comment]
@VoidXH that's exactly what I needed, thank you! I was already writing frame by frame, just needed to change positions before each write.

There's one more question that I wanted to ask, if you think is better I can use another issue to it. I wanted to know if there's a way to set the Dolby Atmos binaural settings (Off/Near/Mid/Far) for each source through Cavern.

**Comment by VoidXH** [comment]
No, that's an encoder setting. For AC-4 binaural, the headphone track is pre-rendered and stored as simple compressed stereo.
