### ISSUE TITLE
Limitless Audio Format Mixed Mode

### ISSUE THREAD

**Issue by Continous** [VoidXH/Cavern#126]
I'm adding this issue here since I'm not sure where the Limitless Audio Format issues should be posted; regardless:

Currently, LAF only supports object mode or bed mode, not both. For some situations it would make sense to have a mixed mode.

**Comment by VoidXH** [comment]
Sorry for the vague documentation. The Mode flag doesn't mean that all tracks must be channels or objects, but the presence of position modification tracks. If Channel mode is set, the LAF file behaves as a kind of losslessly compressed WAV (with the optimization of silent parts not being exported). If Object mode is set, the tracks don't represent placements of fixed angles, but any position in space, updated periodically.

Object mode is technically the Mixed mode, as it also allows you to have channels, just don't update the positions in any frame. This is how "channels" are also contained in E-AC-3 + JOC mixes. Channel array support among the supported formats is only in ADM BWF, but that feature is not part of Cavern. That can be achieved with object sizes though.

**Comment by Continous** [comment]
I'm glad to hear back from you so soon. I actually posted this as a separate project, which exports object-based audio from Blender, pointed out that it seemed LAF didn't have a mixed mode. Glad to have that cleared up for everyone.
