### ISSUE TITLE
Cavernize Live

### ISSUE THREAD

**Issue by VoidXH** [VoidXH/Cavern#128]
Do the real-time version finally with the following steps:
1. Use [DirectShowLib](https://www.nuget.org/packages/DirectShowLib.Standard) in a .NET *Framework* library.
2. Create a Filter from one of the examles that takes E-AC3 and outputs PCM.
3. Call the necessary Cavern decoders and render the samples to PCM using the user's setup set in the Driver.
4. Add an installation class in the library that calls regasm on the filter DLL. This requires admin privileges.
5. Add options in both the Driver and Cavernize to install or uninstall the real-time filter.
6. Add a tutorial to the Documentation that opens after installation regarding the steps to add the filter into MPC-HC.

**Comment by joaoserra** [comment]
How about external audio from HDMI capture cards what support S/PDIF raw extraction (Magewell cards with their capture SDK) (JOC only of course, i know cavern doesn't support DolbyMAT2.0/TrueHD)

Another option would be to capture from S/PDIF capture cards (https://github.com/jakemoroni/audio_async_loopback)

Is this something you will be looking?

**Comment by VoidXH** [comment]
> Is this something you will be looking?

If there is an extensible solution for not external, but internal bitstream capture, that would solve local playback.

**Comment by VoidXH** [comment]
This issue is closed as there will be a complete media player using Cavern.
