### ISSUE TITLE
Some strange code

### ISSUE THREAD

**Issue by ValZapod** [VoidXH/Cavern#13]
https://github.com/VoidXH/Cavern/blob/6bd03619666ff816f63a275122e2a1f66616ac12/CavernSamples/CavernizeGUI/Track.cs#L99

So you check Renderer != null, yet before you dereference it.

https://github.com/VoidXH/Cavern/blob/81fc7366ac637b9a3181f794e5c50527be791413/Cavern/Filters/SpikeConvolver.cs#L51

Strange, SpikeConvolve accepts impulse first.

https://github.com/VoidXH/Cavern/blob/7c752fc9cc4d87d43e5740aa9b407705dc0e92b6/Cavern/Channel.cs#L145-L146

Second current.lowFrequency is always false, we are in ":" of current.lowFrequency.

https://github.com/VoidXH/Cavern/blob/3dc2e42aba80fc5c0c93d13de4f2dbd3e7e148c5/Cavern/Listener.cs#L263

This is not used after that?

https://github.com/VoidXH/Cavern/blob/9fc10ee78980fc94ebcd859c548834d2557211ac/Cavern.QuickEQ/Format/FilterSet/MultEQXpander.cs#L99

pos == -1 can be removed, it is always false. IndexOf('"') above can return -1, but you add 1... Same on line 95?

https://github.com/VoidXH/Cavern/blob/6755aacdea117c02218ef5a49278ce8a9dbad257/Cavern.QuickEQ/EQCurves/EQCurve.cs#L74

It is sampleRate first...

https://github.com/VoidXH/Cavern/blob/8fbe51f00a96ab6d74d4da939530a6c583729ce2/CavernSamples/CavernizeGUI/MainWindow.xaml.cs#L297

This is no malloc, it will fail on new.

**Comment by VoidXH** [comment]
Related commit: 31c2ddbab03a78294061572d0a0b519f94d391b7

> So you check Renderer != null, yet before you dereference it.
It's dereferenced where Supported is true, which can only be true if Renderer is not null and is not a dummy.

> Strange, SpikeConvolve accepts impulse first.
True, fixed, but since f*g=g*f, this didn't cause any issues.

> Second current.lowFrequency is always false, we are in ":" of current.lowFrequency.
Correct, fixed.

> This is not used after that?
No, it's a removed feature. The line is skipped for compatibility with old save files.

> pos == -1 can be removed, it is always false. IndexOf('"') above can return -1, but you add 1... Same on line 95?
Fixed.

> It is sampleRate first...
Also fixed.

> This is no malloc, it will fail on new.
The issue was not this, but it's fixed.

**Comment by ValZapod** [comment]
This one is still https://github.com/VoidXH/Cavern/blob/8aba8f00b23b54b3a1f377e36f8f10e6f4e9e8a5/Cavern.QuickEQ/Format/FilterSet/MultEQXpander.cs#L115

pos == -1 always false.

**Comment by VoidXH** [comment]
Not anymore.
