### ISSUE TITLE
Problem with the reference levels of the Dolby tests

### ISSUE THREAD

**Issue by ChestZ** [VoidXH/Cavern#14]
Hello, 
Thanks for your application.

When decoding the Dolby reference file : 
https://download.dolby.com/us/en/test-tones/dolby-test-tones_7_1_4.mp4
with Cavernize GUI to PCM interger with 7.1.4 Render target, the level of the 12 channels is not identical.
We obtain with an RMS measurement :
-21,34 dB; -21,35 dB; -21,35 dB; _-16,47 dB_; -23,91 dB; -23,92 dB; -24,03 dB; -24,04 dB; -18,25 dB; -18,25 dB; -18,26 dB; -18,25 dB

With the ADM conversion, we obtain identical reference levels, except for the LFE which is normal : 
_-16,21 dB_; -21,35 dB; -21,35 dB; -21,35 dB; -21,26 dB; -21,26 dB;-21,02 dB;-21,03 dB;-21,28 dB;-21,27 dB;-21,28 dB;-21,32 dB

The difference in level is for the surround and top channels, the front channels have the right levels.

Thanks

**Comment by ValZapod** [comment]
> With the ADM conversion, we obtain identical reference levels, except for the LFE which is normal :

That does not have any referece levels, that fire is not channel wav. It is object ADM.

**Comment by VoidXH** [comment]
> That does not have any reference levels, that file is not channel wav. It is object ADM.

There's only one audible object at a time, the volume difference is still caused by Cavern's mixer for some reason which needs fixing.

**Comment by ValZapod** [comment]
> volume difference is still caused by Cavern's mixer for some reason which needs fixing.

But ADM is converted (rendered) to channel PCM. Would not change reference levels in ADM change PCM?

**Comment by VoidXH** [comment]
> But ADM is converted (rendered) to channel PCM. Would not changing reference levels in ADM change PCM?

Changing the mixer won't affect ADM, because ADM is exported without mixing to the selected environment.

**Comment by VoidXH** [comment]
Levels are correct in 1475f9edf51f99d49fca109e7939e80e0de63ba9 and the latest binary release. In this file's case, the overall gain is -3 dB, this can change from content to content and is normal.

**Comment by ValZapod** [comment]
Yes, I can see now it has last 4 channels the same amplitude as the others l, exccept LFE. But it is now slighly lower, is that expected?

@ChestZ Can you verify that you like it? BTW, I remember on Blu-ray there was some difference in these test tones.

**Comment by VoidXH** [comment]
> But it is now slighly lower, is that expected?

Yes. Atmos content is always mixed lower.

**Comment by ValZapod** [comment]
> overall gain is -3 dB, this can change from content to content and is normal.

Are you accoubting for all 4 possible -3db places or when it is not -3db? That van be all configured in Dolby Media encoder.

**Comment by VoidXH** [comment]
Not those gains, the JOC matrix.

**Comment by kaedewang** [comment]
![图片](https://user-images.githubusercontent.com/67850015/210697362-4e8eb622-6bd3-4755-b290-05c91398d667.png)
I decode https://download.dolby.com/us/en/test-tones/dolby-test-tones_7_1_4.mp4 by cavern.
But I think there are some problems, please check:
1. channel 5/6<->7/8 order is reversed with DRP.
2. channel 12(trr) is very strange, it outputs with channel 9(tfl) together.
3. When 1 channel is outputing, others are not mute.

**Comment by VoidXH** [comment]
Reproduced, tracked in #56.

**Comment by VoidXH** [comment]
Fixed and released, the bug was the top rear right's incorrect location. The channel order is correct in Cavernize, all PC standards use F R C LFE RL RR SL SR as the beginning, this includes WAV. Cavern is using WAVEFORMATEXTENSIBLE, which means the channels are labeled and players/converters can use this information to remap them when needed.
