### ISSUE TITLE
ASIO support 

### ISSUE THREAD

**Issue by hgetta** [VoidXH/Cavern#144]
Currently I am trying to measure a 7.2.4 setup with cavern but I am having some issues with the channelcount. The wdm driver for my interface only supports 8 channels but with asio all 13 work fine. It seems like cavern doesn’t support asio drivers at the moment which would be great since people without interfaces could use hdmi for 8 channels and people like me can use indefinite amounts. 

Is there any workaround for low channel counts? i.e. measuring in two steps? Currently I am just measuring a stereo setup multiple times.

**Comment by VoidXH** [comment]
Unity does not support ASIO, but multichannel systems can be measured in two parts. Its tutorial and alignment software is on the bottom of the [StormAudio export guide](https://cavern.sbence.hu/cavern/doc.php?p=Export&tab=sa). Its source code is [here](https://github.com/VoidXH/Cavern/tree/master/CavernSamples/QuickEQResultMerger).

**Comment by hgetta** [comment]
Maybe not applicable for you hit tjere is a unity plugin for asio. 

It costs 15$ though 
https://assetstore.unity.com/packages/audio/sound-fx/low-latency-multichannel-audio-147091

**Comment by VoidXH** [comment]
That's not a real-time plugin. There is another way though, you can generate measurement signal files for any channel count, and if you can play them on ASIO, just press the Start measurement button at the same time. Or you can record it in Audacity and import that.
