### ISSUE TITLE
Streaming instead of converting?

### ISSUE THREAD

**Issue by hoangtu92** [VoidXH/Cavern#15]
Hello, thank you for your hard work to make such a brilliant application. To be able to decode/render dolby atmos video and output to PCM channel using exists 7.1 audio card is great, but i wonder would it be better if we can make this as a codec or something and use it for streaming atmos audio/video without having to convert it or passthrough an avr to be able to have height channels? Im very interested in making it happens, but i dont know how to do it.

**Comment by VoidXH** [comment]
This will happen, as a standalone player, but not as a passthrough device (no such input hardware exists). This is however in the far future, and will be launched as a completely new project.
