### ISSUE TITLE
Linux/PipeWire Support

### ISSUE THREAD

**Issue by RageGamerBoi** [VoidXH/Cavern#152]
I've been playing around with Linux audio things and had an idea to jerry-rig together a 7.1.4 setup from a ton of random speakers and some USB audio interfaces cheap off of wherever.

| PipeWire setup for first demo  | Second demo to test overhead speakers |
| ------------- | ------------- |
| ![Surround-Sound](https://github.com/VoidXH/Cavern/assets/105567407/9796387d-b14d-447c-a005-9144d103fa44) | ![Snapshot_2024-02-23_18-03-19](https://github.com/VoidXH/Cavern/assets/105567407/7070d870-6048-469f-977f-39fb9a523832)  |
| This worked surprisingly well if you can look past how I connected three separate sets of speakers using three different physical audio outs | Normal surrounds worked (when patched to my test output) but overhead outputs did not produce any sound at all, even when playing Dolby Atmos content |

This lead me to find out that Atmos decoding essentially isn't supported by any Linux program as far as I can tell, and only Atmos pass-through (to a dedicated receiver) works with things like [Kodi](https://kodi.tv/)

After much deliberation I came across this and was super excited until I found out it was effectively Windows only (running through Wine didn't work out too well for me), and that live processing appears to be non-existent as of yet.
Is a fully-featured Linux option with proper real-time [PipeWire](https://www.pipewire.org/) ([docs](https://docs.pipewire.org/)) support planned or at least a possibility?

**Comment by VoidXH** [comment]
MAUI migration will make Linux builds possible, it's tracked in #123.
