### ISSUE TITLE
Cavern Driver 1.5 no sound when playing E-AC-3 JOC file

### ISSUE THREAD

**Issue by dechamps** [VoidXH/Cavern#16]
I just discovered this project and got curious, so I rummaged through my content and found an E-AC-3 JOC file to use as a quick test. Here's a 10-second sample of the file: [E-AC-3 JOC test.zip](https://github.com/VoidXH/Cavern/files/9690702/E-AC-3.JOC.test.zip)

Cavern Driver 1.5 successfully opens the file and seems to show the objects as well as player controls:

![image](https://user-images.githubusercontent.com/866859/193417914-77acec02-aa24-4760-90be-3902957ee3cb.png)

But there is no sound, and all the levels read zero as shown in the screenshot.

The file plays fine in various other players (although to be clear, the other players I tried it with only support the base E-AC-3 layer).

Is this expected? I was under the impression that Cavern Driver could be used to play such files?

Here's what MediaInfo has to say about the file:

```
General
Complete name             : Y:\tmp\E-AC-3 JOC test.mkv
Format                    : Matroska
Format version            : Version 4
File size                 : 942 KiB
Duration                  : 10 s 27 ms
Overall bit rate mode     : Constant
Overall bit rate          : 770 kb/s
Writing application       : Lavf59.27.100
Writing library           : Lavf59.27.100
ErrorDetectionType        : Per level 1

Audio
ID                        : 1
Format                    : E-AC-3 JOC
Format/Info               : Enhanced AC-3 with Joint Object Coding
Commercial name           : Dolby Digital Plus with Dolby Atmos
Format settings           : Big
Codec ID                  : A_EAC3
Duration                  : 10 s 27 ms
Bit rate mode             : Constant
Bit rate                  : 768 kb/s
Channel(s)                : 6 channels
Channel layout            : L R C LFE Ls Rs
Sampling rate             : 48.0 kHz
Frame rate                : 31.250 FPS (1536 SPF)
Bit depth                 : 32 bits
Compression mode          : Lossy
Stream size               : 454 MiB
Language                  : English
Default                   : Yes
Forced                    : No
Complexity index          : 16
Number of dynamic objects : 15
Bed channel count         : 1 channel
Bed channel configuration : LFE
```

**Comment by ValZapod** [comment]
>But there is no sound, and all the levels read zero as shown in the screenshot.

You need to decode to 24 bit wav with drc_scale 0 using ffmpeg (under the same name).

**Comment by dechamps** [comment]
> You need to decode to 24 bit wav with drc_scale 0 using ffmpeg (under the same name).

I'm confused as to what you're asking me to do. My understanding is that ffmpeg doesn't support audio objects. If I decode the file using ffmpeg, I will lose the object information, which defeats the point of this exercise as I want to visualize and listen to the objects using Cavern. Did I misunderstand your suggestion?

**Comment by ValZapod** [comment]
>Did I misunderstand your suggestion?

No. Cavern driver will still read metadata from eac3. It just cannot deocde audio from it, only from wav.

**Comment by VoidXH** [comment]
You need the decoded 5.1 or 7.1 track as a WAV with the same name next to the source MKV, the objects are mixed from it. Currently Cavern doesn't decode the PCM part as FFmpeg does it better, but it will in the future. Complete remixing is handled automatically in Cavernize GUI, however. Currently this is the expected behavior, but will be changed in the future.

**Comment by ValZapod** [comment]
>Currently Cavern doesn't decode the PCM part as FFmpeg does it better, but it will in the future

Maybe it would make sence to use ffmpeg too like in Cavernize GUI. Also, it is funny how it cannot open another file after I played one or that I cannot pause it.

**Comment by VoidXH** [comment]
PCM decoding is nearly done, it will be included in the Driver. There are problems with implementation (marked with a TODO) that break simultaneous playback of 2 AC-3 streams, but it will be fixed.

**Comment by VoidXH** [comment]
PCM decoding finished, released.

**Comment by ValZapod** [comment]
@dechamps Did you make it work for you? ✨️✨️

**Comment by ValZapod** [comment]
@dechamps New version allows to just open mkv files.

**Comment by VoidXH** [comment]
Also .ac3 and .ec3.

**Comment by dechamps** [comment]
I'm a bit confused - where do I find the new version? Both the Cavern website and the GitHub releases page show the latest version is still 1.5. Should I build it from source?

**Comment by VoidXH** [comment]
You also need to look at the release date. Yeah, it's versioned poorly in beta.

**Comment by ValZapod** [comment]
>Should I build it from source?

It is closed source. This repo is only part of it.

**Comment by dechamps** [comment]
Ah. The version currently on the website seems to work, yes. I just spotted one small bug where seeking doesn't work after the file has finished played, but it's benign. Thanks!
