### ISSUE TITLE
Linux QuickEQ Support

### ISSUE THREAD

**Issue by TsunamiMommy** [VoidXH/Cavern#162]
Hi there,
I would dearly love to see even just the quickEQ portion of the software working on linux. It is simply the best speaker calibrator out there. I do ambisonic encoding/decoding and I use an external atmos decoder for live content. Is this something in the pipeline? I'm not really worried about the atmos encoding/decoding. I would just love to use it with JACK2 on my linux setup.

**Comment by VoidXH** [comment]
There is a plan of releasing Linux and Mac builds after the API is considered stable, but current builds are nightlies. QuickEQ's results can be used in the meantime with CamillaDSP convolution exports on Linux.
