### ISSUE TITLE
[REQ] Add a (GH-compliant) license file

### ISSUE THREAD

**Issue by forart** [VoidXH/Cavern#163]
Hi there, 1st of all thanks for this cool work !

Since we've "doxed" it in our [HyMPS project](https://github.com/forart/HyMPS#readme) (under the [AUDIO category](https://github.com/forart/HyMPS#-) \ [Engines page](https://github.com/forart/HyMPS/blob/main/A_Engines.md#--), can you please add a (GH-compliant) license file ?

Although it may sounds like a minor aspect, license file omission causes an inconsistent generation of the relative badge too:

![](https://flat.badgen.net/github/license/VoidXH/Cavern/?label=LICENSE)
(badge-generator URL: https://flat.badgen.net/github/license/VoidXH/Cavern/?label=LICENSE)

Anyway you can also easily set a "correct" one through the GH's license wizard tool.

Last but not least, let us know - in your opinion - how we could improve our categorizations and links to resources in order to favor collaboration between developers (and therefore evolution) of listed projects.

Thanks in advance.

**Comment by VoidXH** [comment]
Added in da636cfa7b065a8d6aeb7b52716c6b7664edcc24.

**Comment by forart** [comment]
Thanks, I'll manually set the badge to "Other" (since the license it's not a standard one) then.
