### ISSUE TITLE
What format for game audio?

### ISSUE THREAD

**Issue by Sawtaytoes** [VoidXH/Cavern#165]
Game audio in Windows using the Spatial Audio API outputs to Dolby MAT or whatever DTS:X uses.

I'm curious how I can record this game audio in a way that it'll play back in Cavern Driver. For instance, if I want to see how many objects are being used in a game (rather than bed layer speakers), is that possible?

**Comment by VoidXH** [comment]
There is no recording endpoint (neither too many others) in the Spatial Audio API. You could rip it from the HDMI bitstream with a Blackmagicdesign card, but then you'd be at the same position as #166. Games don't use objects anyway, there's a thing called ISF for it. Objects are pre-rendered, and the output is strictly 7.1.5 (yes, 5). The only way to confirm this is currently through the Trinnov visualizer.

**Comment by Sawtaytoes** [comment]
What's ISF?

Also, if objects are pre-rendered, that explains why they don't show up in the Trinnov Visualizer. Someone on AVS forums had posted about that.

I'm curious about `7.1.5`. What's the 5th height speaker supposed to be? Is it supposed to have audio come out from your AVR?

**Comment by VoidXH** [comment]
ISF is intermediate spatial format, made as a space saver for specific pre-rendered, thus technically channel-based content. The channels in ISF formats are undocumented. Trinnov displays them, but their order will still be undocumented.

**Comment by Sawtaytoes** [comment]
>You could rip it from the HDMI bitstream with a Blackmagicdesign card

Which card in particular? You mean a PCIe one? Is there a USB device I could use to record the HDMI bitstream? Or is this something where I have to send the audio to a separate HDMI device (fake monitor) rather than sending it to my AVR?

**Comment by VoidXH** [comment]
Some DeckLink cards have HDMI inputs, however, no HDCP. Their API is completely open, you can make an audio separator script without actually owning a card.
