### ISSUE TITLE
Why no Dolby TrueHD?

### ISSUE THREAD

**Issue by Sawtaytoes** [VoidXH/Cavern#166]
Is the reason Cavernize doesn't support Dolby TrueHD because there's no documentation on how to do it?

My workaround is to record all the pre-out outputs from my AVR, but it'd be easier if I could do it in software since I wouldn't have to play the whole thing to record it.

As far as I'm seeing, TrueHD is also not supported in Cavern Driver from the same reason?

**Comment by VoidXH** [comment]
There is an [explanation](https://cavern.sbence.hu/cavern/doc.php?p=Cavernize&tab=cd) next to the Cavernize download. In short, it would require a *complete* low-level documentation, not just the header documentation what is available now.

[There is a way](https://audiophilestyle.com/ca/immersive/how-to-decode-and-play-dolby-truehd-atmos-on-windows-and-macos-r1092/) to losslessly create 9.1.6 exports faster than real-time, but it costs $400 for the Dolby Reference Player.

**Comment by Sawtaytoes** [comment]
> [There is a way](https://audiophilestyle.com/ca/immersive/how-to-decode-and-play-dolby-truehd-atmos-on-windows-and-macos-r1092/) to losslessly create 9.1.6 exports faster than real-time, but it costs $400 for the Dolby Reference Player.

What's this mean? I can buy this software if it helps me. Are you saying Dolby Reference Player can take a TrueHD Atmos track and _also_ export a 16-channel WAVE file rendered for a given speaker configuration like 7.1.6?

Also, is this different from the Dolby Atmos Renderer? Or are you supposed to use both in tandem?

**Comment by VoidXH** [comment]
> Are you saying Dolby Reference Player can take a TrueHD Atmos track and _also_ export a 16-channel WAVE file rendered for a given speaker configuration like 7.1.6?

Not for a given configuration, its 7.1.6 is fixed, but you can use Cavernize to reorder or rerender it. They improved this process since, look at the comments and the Quadraphonic Quad forum.

> It looks like Cavernize is similar to Dolby Reference Player and Cavern Driver is like the Dolby Atmos Renderer. Is that correct?

Both are based on the renderer, the Driver is like an AVR, and Cavernize is like DRP, it exports to files, so a media player with extra steps.

> Also, is this different from the Dolby Atmos Renderer? Or are you supposed to use both in tandem?

DRP is one implementation of an Atmos Renderer.

**Comment by ThreeDeeJay** [comment]
👀 🤔  https://github.com/truehdd/truehdd

**Comment by VoidXH** [comment]
Guess #241 is on. Nice find!
