### ISSUE TITLE
Selecting User Preset makes the room larger

### ISSUE THREAD

**Issue by Sawtaytoes** [VoidXH/Cavern#168]
When I select the User Preset I made, the room keeps getting larger and larger each time I click it. This isn't the same I used. My room is actually pretty small, and Cavern Driver doesn't let me shrink the room to that size either (12' x 11' x 9'). Is it growing like this because my 11' size was set to the minimum 3.5m?

![image](https://github.com/VoidXH/Cavern/assets/3948069/9545752b-55d8-4e08-a7e3-1d2606c56fd2)

**Comment by VoidXH** [comment]
Is this reproducible with any preset? Could you please attach one? They're located under %appdata%/Cavern.

**Comment by Sawtaytoes** [comment]
[CavernPreset_Living Room.zip](https://github.com/VoidXH/Cavern/files/14969390/CavernPreset_Living.Room.zip)

**Comment by VoidXH** [comment]
The preset is correct, contains a 3.6x3.5x2.8 room. Stuck keys can cause such issue, for example, if you press right continuosly, the first dimension grows. One down button press and the next dimension grows. Do you have a video of how this happens?

**Comment by VoidXH** [comment]
Hi @Sawtaytoes, is it still reproducible?

**Comment by VoidXH** [comment]
Please reopen the issue if it's reproducible.
