### ISSUE TITLE
E-AC-3 JOC file decode produces distorted output

### ISSUE THREAD

**Issue by dts350z** [VoidXH/Cavern#17]
Version 1.5

Decoding E-AC-3 JOC music files (commercial and self encoded) to riff produces distorted results. I am comparing to the reference player.

7.1.4 layout to integer RIFF.

Also RIFF float settings  produce 16bit results

**Comment by ZaquL** [comment]
Well, where are the sample eac3 and sample wav from drp.exe? LOL.

**Comment by dts350z** [comment]
Copyright

Maybe a short section?

**Comment by ValZapod** [comment]
>Also RIFF float settings produce 16bit results

Well, do not use it then. 24 bit decoding is a must.

**Comment by dts350z** [comment]
[30sec clip -17.84 lufsDDP.zip](https://github.com/VoidXH/Cavern/files/9691188/30sec.clip.-17.84.lufsDDP.zip)
Drums in top channels are distorted.

Re bit depth, everything RIFF decoded is tagged 16bits in wav header.

**Comment by ValZapod** [comment]
That is the ONLY issue you have?

**Comment by dts350z** [comment]
Distortion and no 24 bit out for RIFF decoding, yeah.

**Comment by ValZapod** [comment]
Does the bug happen at ADM stage (object extraction) or rendering? Can you somehow attach 9.1.6 render of Dolby Reference player?

**Comment by dts350z** [comment]
[30sec clip -17.84 lufsDDP_Reference Player_trimmed for size.zip](https://github.com/VoidXH/Cavern/files/9693714/30sec.clip.-17.84.lufsDDP_Reference.Player_trimmed.for.size.zip)

16 ch 24bit digital recording of reference player output. Had to be trimmed, front and back, for the zip to fit in the 25MB attachment limit here.

ADM output of canvernizeGUI, played back in adobe audition, also sounds distorted.

**Comment by ValZapod** [comment]
Can you put not trimmed version somewhere too?or multipart archive if you insist.

**Comment by dts350z** [comment]
This is the full clip:

https://drive.google.com/file/d/12Uv0gNKNS6IlpMmZall8EqKbZvs-LF5c/view?usp=sharing

FYI it still won't be time aligned with the encoded version because the digital recording is manually started and stopped, before/after the player is started and stops.

I suppose if you trimmed of everything before the first non-zero sample, it would start at the right place.

Please let me know, after you've grabbed it and confirmed,  and I'll take it down.

**Comment by ValZapod** [comment]
Got it.

**Comment by ValZapod** [comment]
Git it.

**Comment by VoidXH** [comment]
There are two types of JOC coding, coarse and sparse. Coarse, which is widely used by movies, works without issues, sparse (found in some versions of amaze) doesn't, as the documentation is incorrect about it. I'll contact Dolby about this, but the fix to the standard never comes fast.

**Comment by ValZapod** [comment]
BTW, I see that this https://www.etsi.org/deliver/etsi_ts/103400_103499/103420/01.02.01_60/ts_103420v010201p0.zip has nore tables that you use. Is that related?

**Comment by VoidXH** [comment]
All of these are in JointObjectCodingTables.cs.

**Comment by ValZapod** [comment]
float prot64[640] isn't?

**Comment by VoidXH** [comment]
That's in QuadratureMirrorFilterBank.cs, sorry.

**Comment by ZaquL** [comment]
Short section under fair use is fine. Remember DRP.exe can apply DRC. We do
not want that.

**Comment by VoidXH** [comment]
After trying (and failing in) every interpretation of the standard's related parts, I've sent a mail to Dolby. If they reply, I'll reopen and fix this issue.

**Comment by bluewidy** [comment]
Sir, after all they didn't reply?

**Comment by VoidXH** [comment]
No.

**Comment by ValZapod** [comment]
>because the digital recording is manually started and stopped, before/after the player is started and stops.

FYI, there is no need to use VB audio ot VAC (virtual audio cable) and decoding stuff realtime: you can just use this script, since DRP is based on gstreamer. You need python 3.11.1... https://gist.github.com/Plazik/e950267cc580bcde371ea7879aaa3d5d
