### ISSUE TITLE
All good quality films are now systematically in Atmos Dolby TrueHD

### ISSUE THREAD

**Issue by AntPradZT** [VoidXH/Cavern#170]
Hello! And a huge thank you for the amazing work you do here, I'm very lucky to have found Cavernize. I just wanted to tell you about a problem I have: Downloading the best possible image quality, I was initially confronted with the fact that in the best MKVs there is only TrueHD and not compatible DDP with Cavernize. So I got two, one for the image in super quality, one for the sound in DDP, then I merged them all. Except that for the past year, I have the impression that new films are only in TrueHD and I can no longer find a DDP version. Is there a quick solution to convert TrueHD to DDP to make them compatible with Cavernize?

**Comment by VoidXH** [comment]
There is no openly awailable way to convert TrueHD to anything else and it's closed source, [this is why it can't be supported by Cavern.](https://cavern.sbence.hu/cavern/doc.php?p=Cavernize&tab=cd)

**Comment by AntPradZT** [comment]
I was hoping there was a solution, like for example FFmpeg

Le mer. 15 mai 2024 à 12:56, Bence Sgánetz ***@***.***> a
écrit :

**Comment by AntPradZT** [comment]
Hi Bence!

I hope you are fine. I have just taken new films in excellent quality,
their size is between 15 and 50 GB each time, and they are all in MKV. When
I convert them in Cavernize to ADM (Dolby Atmos), depending on the films,
if I play with VLC I get either silence or saturated sound. When I then put
them back into DACT, select ADM and 23.976FPS, it works for a long time to
make a new file but the result is the same with silence or overdrive. I'm
on a new AMD computer with Windows 11 but I'm having the same problem with
another Intel computer on Windows 10. Here's a short clip I cut out with
DACT to show you.
Thx in advance for your advice!
[image: Capture d'écran 2024-05-15 185444.png]
[image: Capture d'écran 2024-05-15 200126.png]
[image: Capture d'écran 2024-05-15 200105.png]

Top.Gun.Maverick.2022.2160p.DDP5.1.Atmos.HDR.H.265-SHORT-EXCERPT-FOR-BENCE.wav
<https://drive.google.com/file/d/1qyLnCGwOH-5t8GMN_HyR-MN9D9B_8xR0/view?usp=drive_web>

**Comment by AntPradZT** [comment]
Victory! In fact it worked for 3 films out of 6. The correction technique
with DACT does indeed work but the problem comes from the conversion with
cavenize for these 3:

Dune.2021.2160p.HMAX.WEB-DL.DDP5.1.Atmos.HDR.HEVC-EVO[TGx]
Dune.Part.Two.2024.2160p.WEB-DL.DDP5.1.Atmos.DV.HDR.H.265-FLUX[TGx]
Top.Gun.Maverick.2022.2160p.WEB-DL.DDP5.1.Atmos.HDR.H.265-EVO[TGx]

Basically on the 25 tracks there is the same mixture of sounds from the
film, "saturated", it looks like a weird distortion, an audio encryption.

But it worked for these 3 (YEAAAHHH):

Avatar.The.Way.of.Water.2022.2160p.WEB-DL.DDP5.1.Atmos.DV.HDR10.HEVC-CMRG
The.Batman.2022.2160p.HMAX.WEB-DL.DDP5.1.Atmos.HDR.HEVC-CMRG[TGx]
No.Time.to.Die.2021.2160p.WEB-DL.DDP5.1.Atmos.HDR.HEVC-EVO[TGx]

**Comment by VoidXH** [comment]
I just tried one of the non-working movies (Dune.2021.2160p.HMAX.WEB-DL.DDP5.1.Atmos.HDR.HEVC-EVO[TGx]), but it converted successfully with the latest release. What is a problematic timestamp, and what settings (container, codec, channel layout) are used?

**Comment by AntPradZT** [comment]
Hello Bence !

Thank you very much for your email. It's a wave of hope for me, it feels
good! I think I hadn't changed anything in the settings, except blocking in
24 bit (I know that it doesn't change anything in quality, don't worry,
it's just for importing into ProTools), and since I only want ADMs, there
is no possible problem with the channel order. Each time, as you explained
to me, I go through the Dolby Atmos Conversion Tool so that the ADM works
when importing into Pro Tools and Nuendo. But even before that, I can
recognize the exports that don't work as soon as Cavernize exits by opening
them with VLC: When I don't hear any sound, it's because the ADM will work
after the DACT. But when VLC plays sound, it's always a weird sound as if
saturated by a digital interpretation problem, and all the channels (Bed,
objects, everything) have the same mixed sound.
If I can help you in any way in finding the problem, don't hesitate! Good
luck and see you soon I hope!

Antoine Pradalet

Le lun. 5 août 2024 à 23:48, Bence Sgánetz ***@***.***> a
écrit :

**Comment by VoidXH** [comment]
Same as #193. Not reproducible, likely a DAW bug. If Audacity can decode it, there's nothing I can do, because the file is standard.

**Comment by AntPradZT** [comment]
Hello Bence,

The problem is not related to the Daw, it is the same in Audacity. Moreover
I noticed this: The ADMs that will work are silent in VLC before even going
through the Dolby Atmos Converter. Those that will not work have this
problem on VLC (before and after going through the Dolby Atmos Converter),
we hear the saturated film and the sound is the same on all tracks.



Le lun. 4 nov. 2024 à 14:02, Bence Sgánetz ***@***.***> a
écrit :
