### ISSUE TITLE
Add TrueHD Atmos

### ISSUE THREAD

**Issue by GardenMalcom** [VoidXH/Cavern#177]
It works with AC3 Atmos but not working with TrueHD Atmos so Please Add TrueHD Atmos Support.

![1](https://github.com/VoidXH/Cavern/assets/139205711/3dcbdd94-d538-4d9a-98d0-0c85bd32edde)
![2](https://github.com/VoidXH/Cavern/assets/139205711/ac545e36-d050-4e60-97e3-713b2f886fdf)

**Comment by VoidXH** [comment]
It's not possible. [Read more](https://cavern.sbence.hu/cavern/doc.php?p=Cavernize&tab=cd)
