### ISSUE TITLE
Is it possible to add 5.1 downmix settings to Cavernize's "Show metadata" feature?

### ISSUE THREAD

**Issue by bluewidy** [VoidXH/Cavern#178]
![Mediainfo changelog](https://github.com/VoidXH/Cavern/assets/40682277/a3051d72-56c5-454c-af5c-74b1497a299d)

Starting with version 22.03, Mediainfo added an item showing [5.1 downmix settings](https://professionalsupport.dolby.com/s/article/How-do-the-5-1-and-Stereo-downmix-settings-work?language=en_US). So, when I open the ADM BWF file through Media Info, the values ​​appear as follows.
<img width="240" alt="sample1" src="https://github.com/VoidXH/Cavern/assets/40682277/6aa102f5-bfa1-468f-aa34-f35ac9ec0749">
<img width="244" alt="sample2" src="https://github.com/VoidXH/Cavern/assets/40682277/a438c2aa-f4bc-401a-8af7-0caeeb0eb89b">

But this is not the case for ec3-joc or TrueHD files. 5.1 Downmix metadata is not visible.
<img width="362" alt="sample3" src="https://github.com/VoidXH/Cavern/assets/40682277/fad55d1c-8c10-4248-850a-d65c5605935f">

So I looked at the "Show metadata" feature in Cavernize, and it seems to provide a much larger amount of metadata than MediaInfo does.
<img width="1280" alt="Cavernize Show metadata" src="https://github.com/VoidXH/Cavern/assets/40682277/83f7e78f-8394-466d-a0fc-6efc912ae849">
But I can't find any values ​​for the 5.1 downmix settings here either. I wonder if you can add a 5.1 downmix metadata entry.

**Comment by VoidXH** [comment]
This information is not contained in the AC-3 format. Only downmixing levels for the center (cmixlev) and surrounds (surmixlev) are saved, and the downmixing method is the same for all files, it's defined in the standard. The only case where there is a field in the file, is when it was downmixed, then it will contain how it was downmixed - if the encoder supports this feature.
