### ISSUE TITLE
Incorrect Channel Mapping

### ISSUE THREAD

**Issue by jaja123456789** [VoidXH/Cavern#18]
When decoding some files like the Dolby Nature's Fury trailer, the output channels are incorrectly mapped. 
e.x. the dialogue comes out of the left speaker.

On other files the output is correct i.e channels are in the correct order (L R C LFE SL SR...)

- master branch

**Comment by VoidXH** [comment]
What media player do you use? VLC for example is notorious for not respecting channel orders in Opus (center comes from the left), Dune players are also guilty of this behavior. The exported channels always start with L R C LFE.

**Comment by VoidXH** [comment]
A solution might be adding new export formats that have channel mapping burned in (which Opus and PCM doesn't). DTS might be one good candidate, it's also funny to play Atmos movies in a DTS container. TrueHD would also work (both can easily be added), but is needlessly large, as DTS is already both more efficient and higher bitrate than DD+, it should contain it without issues.

**Comment by VoidXH** [comment]
Channel mapping was manually checked and is correct in all cases. It will be a player issue. I couldn't add any Dolby/DTS outputs as FFmpeg only allows up to 6 channels in them. However, I added FLAC in be1afc5aae1845827b5c72ae3f45bd5a7d46aa3b, that might help.

**Comment by ValZapod** [comment]
>TrueHD would also work

Please note my report https://trac.ffmpeg.org/ticket/9958 and that TrueHD can be better than 12 level flac, but only of you use official encoder.

**Comment by VoidXH** [comment]
Is the official encoder free? In that case it could be used instead of FFmpeg, as 7.1 is not supported with the latter.

**Comment by ValZapod** [comment]
Not free, no. ;)

**Comment by ValZapod** [comment]
> Is the official encoder free? In that case it could be used instead of FFmpeg, as 7.1 is not supported with the latter.

BTW, it is smaller because apparently it is 100% lossless, there are like 100 or so bytes all over the place that are different. Anyway, it may still be better if Dolby fixed their encoder (or maybe there is some gotcha bug inside ffmpeg decoder).

**Comment by VoidXH** [comment]
You will always get rounding issues for spectrum-based encodings. TrueHD and btw FLAC too are practically lossless codecs. They do not alter the content in any way, but the precision can take a hit in the last bit.
