### ISSUE TITLE
Audio is distorting on Cavernous - How to Fix

### ISSUE THREAD

**Issue by GardenMalcom** [VoidXH/Cavern#180]
I have rendered more than 5 movies in it, But the thing is, some of the films are distorted and muted, Rest of them are pretty good.

But I know some of the videos are good quality Dolby Atmos. 

the video I'm talking about is Dolby Atmos Demo - Amaze. 

Please HELP ME Fix it.

**Comment by GardenMalcom** [comment]
![Screenshot 2024-06-13 120103](https://github.com/VoidXH/Cavern/assets/139205711/f610d120-2338-459b-85c9-f67ade137890)

**Comment by VoidXH** [comment]
This is a known issue with the Amaze demo as described by the popup. This is a part of the standard that's not described correctly, so these parts can't be decoded.
