### ISSUE TITLE
How to merge the onboard Realtek 7.1 and USB 2.0 sound card

### ISSUE THREAD

**Issue by GardenMalcom** [VoidXH/Cavern#184]
I can't merge the onboard Realtek 7.1 and USB 2.0 sound card. it's a bit difficult for me, can you tell me the simple way to merge in Windows so I can enjoy Dolby Atmos

I tried Asio4all. but I Don't know how to use it.

**Comment by VoidXH** [comment]
While it's out of the scope of this project and I don't know the answer, check out #117 for all info. If a concrete solution is ever found, please add to either this issue or that discussion, and I will update the documentation.
