### ISSUE TITLE
No decoding/playback on recent builds

### ISSUE THREAD

**Issue by ThreeDeeJay** [VoidXH/Cavern#187]
Just a heads up: I just noticed that since [Cavern-Win64_2024-07-17](https://github.com/VoidXH/Cavern/actions/runs/9982514976/artifacts/1712886117)@https://github.com/VoidXH/Cavern/commit/d1860996d8d5c16b12809517a00d08963014c2da (Configuration file project sample rate), trying to play a file results in no audio or moving visuals, besides the seek bar and the virtual screen loop.

The previous/last working build was [Cavern-Win64_2024-07-16](https://github.com/VoidXH/Cavern/actions/runs/9965058277/artifacts/1708449527)@https://github.com/VoidXH/Cavern/commit/6471536fe344ba72082ca947b718bab29331e343

**Comment by VoidXH** [comment]
This issue is not present in Unity Editor, so it's a linking issue. When a new build is released for any reason (one of the current issues get implemented or fixed), it will work again for a while.

**Comment by VoidXH** [comment]
New version uploaded, the next commit is the exact same DLL used in this one.

**Comment by ThreeDeeJay** [comment]
Wait, so was https://github.com/VoidXH/Cavern/commit/70f497958b24c88d66332072f00d42a14f5f7c2c meant to fix it?
Because it still doesn't work with it or the latest commit 🤔 
Or did you mean it'd be fixed once the base build (https://cavern.sbence.hu/index.php?t=115&dl=cavern64) is updated or a new stable release?

**Comment by VoidXH** [comment]
It wasn't the commit, the new build was updated to support the newer DLLs, which the downloadable stable does.

**Comment by ThreeDeeJay** [comment]
btw @VoidXH I just noticed this issue only happens when using the Headphone virtualizer.
When I'm using other modes, it works even on the latest builds.

https://github.com/user-attachments/assets/36a75c74-e70f-43eb-a963-310758788df3

Have you considered using something like OpenAL Soft for object-based audio mixing?
It supports [several channel configurations](https://github.com/kcat/openal-soft/blob/master/alsoftrc.sample#L58-L59) and even [custom layouts](https://github.com/kcat/openal-soft/blob/master/docs/ambdec.txt) like [3D7.1](https://github.com/kcat/openal-soft/blob/master/docs/3D7.1.txt). Not to mention, its HRTF rendering is probably the best FOSS one out there, and allows custom 3D HRTFs for virtualization/spatialization and the dev even made a basic LAF player using it https://github.com/VoidXH/Cavern/issues/146#issuecomment-2274881992  👀👌

**Comment by ThreeDeeJay** [comment]
Quick update: Headphone Virtualizer playback works again as of the latest build 👀👌:
> https://github.com/VoidXH/Cavern/commit/c66153b87df17e3d3b472cb7c774e8903ae12742: Disable PDB generation for Release builds (VoidX)
