### ISSUE TITLE
Problem with decoding to ADM BWF (Dolby Atmos) format

### ISSUE THREAD

**Issue by Slimbizkit** [VoidXH/Cavern#192]
Hello. I have a problem with decoding to **ADM BWF (Dolby Atmos)** format. When I import the received WAV file into the editor, I see that all objects are the same and decoded incorrectly and strangely. And their sound is distorted, the waveform is not standard. Decoding into **ADM BWF (compact)** is **OK**.

I have Windows 10 22H2
ffmpeg version 2024-10-31-git-87068b9600-essentials_build-www.gyan.dev
CavernizeGUI v2.0.2

ADM BWF (Dolby Atmos):
![ADM_BWF(atmos) objects](https://github.com/user-attachments/assets/d007079f-5ca0-45b3-8732-4f834957e7ad)
![ADM_BWF(atmos) waveform](https://github.com/user-attachments/assets/8b39e95a-efd9-485d-926f-8f9e00da29de)
ADM BWF (compact):
![ADM_BWF (compact) objects](https://github.com/user-attachments/assets/747c2106-d134-4776-9305-853e1bcf3d71)
![ADM_BWF (compact) waveform](https://github.com/user-attachments/assets/b7b70399-da0a-4900-bebf-d2b27bda11fd)

**Comment by VoidXH** [comment]
No such issue could be reproduced on latest release with multiple content. This is likely a decoder bug in your DAW. If Audacity or any player after an FFmpeg strip shows the same, I'll reopen the issue, but if they can play the PCM data, this is not a bug in Cavern.
