### ISSUE TITLE
Is there any other way to decode DTS X

### ISSUE THREAD

**Issue by GardenMalcom** [VoidXH/Cavern#198]
Is there any other way to decode DTS X please tell me, brother, because jurassic park 1993 was realised only on DTS X on ton Dolby atmos that's why please guide me I want to decode os badly

**Comment by VoidXH** [comment]
DTS:X is undocumented and as such is practically impossible to implement. [Read more](https://cavern.sbence.hu/cavern/doc.php?p=Cavernize&tab=cd)
