### ISSUE TITLE
Cavern Driver App won't stop rotating the room

### ISSUE THREAD

**Issue by Ralms** [VoidXH/Cavern#2]
Hi there, 

I found about this project today and I find it very interesting. 
I've been looking for some sort of PC based Dolby Atmos decoder as such was giving it a try.

However, while trying to explore the Cavern app, I found it very difficult to do so, as the room won't freaking stop rotating, making it almost impossible to place any object. 

Would it be possible to add an option to stop the room rotating or is it a bug? 

Thanks.

**Comment by VoidXH** [comment]
Could be a bug or a key that was pressed but its release was not passed to the application. Does it happen every time? Does it stop when you press each of the WASD keys and the arrows?

**Comment by ValZapod** [comment]
Does not happen here. I cannot make it spin that is. Not that I can make it work either report does not work, export stops working, etc.

**Comment by VoidXH** [comment]
> I've just narrowed it down to Cavern using my Simracing pedals for some reason.

So it's only when the pedals are connected? In this case, the workaround until update is to disconnect or disable the pedals. I'll add a deadzone in the next pre-release. In this case, the issue can be closed.

> Does not happen here. I cannot make it spin that is. Not that I can make it work either report does not work, export stops working on rendering stage, etc. Unity app does work on ADM WAV (not 16 channels though), but it does not appear to be ADM? Davinci does not recognize it?

Please download or build the latest version of Cavernize GUI. It's just released with a version display, you'll know if you're on it, it has the update which was validated through Dolby's similar software for ADM. AC-3 support was cut from the Driver when length was only provided for containers by Cavern.Format, but now it's fixed, and will be included in the next version. Please send me samples that cause issues with the newest release.

**Comment by ValZapod** [comment]
> AC-3 support was cut from the Driver when length was only provided for containers by Cavern.Format, but now it's fixed

I do not know how to link Unity everything with Driver to get it working in Visual Studio 2022. Maybe you can update it on site?

**Comment by VoidXH** [comment]
> I do not know how to link Unity everything with Driver to get it working in Visual Studio 2022. Maybe you can update it on site?

It will be included in the next release. Temporary workaround is in #4.

**Comment by VoidXH** [comment]
Increased analog dead zones from 0.1% to 10% in the Driver. This will be included in the next release.

**Comment by Ralms** [comment]
@VoidXH just noticed the "fix" and there seems to be a miss conception with the issue. 

Sim Racing pedals don't have their Axis at the middle, they go from 0% to 100% on all Axis. 
As such, if threaded like a Gamepad (which they aren't), will result on the app to consider an axis is turned all the way left.

Here a screenshot as an example:
![image](https://user-images.githubusercontent.com/1717049/191131747-a3d8b23c-f627-442e-976b-94b98bc245e5.png)

X is maxed as I pressed the Accelerator pedal. 
Y is Brake, not pressed. 
Z is Clutch (don't have one connected but my controller supports it). 

As such, its not a question of dead zones, it kinda doesn't have one, and more around knowing the Game Controller type (if possible). 

Hope it helps.

**Comment by VoidXH** [comment]
Now this complicates things. I'll make a toggle for controller support.

**Comment by VoidXH** [comment]
Toggle added, scheduled for release.

**Comment by VoidXH** [comment]
Released.
