### ISSUE TITLE
Unable to use Cavernize Headphone Virtualization

### ISSUE THREAD

**Issue by EaryChow** [VoidXH/Cavern#202]
Been recommanding Cavernize to people in some online chats and they tried the headphone virtualization rendering, which didn't work for them, I tried it as well and it didn't work for me either.

Steps: 
1. Launch Cavernize and load an EAC3 file, choose headphone virtualization as target format, hit render now
2. It says "Starting render", the chosen folder also has the temp .wav file created, but the progress bar remains empty and is stuck there forever, 

Then I thought it's probably because I didn't load any HRTF files, so I downloaded some from : https://www.york.ac.uk/sadie-project/database.html

3. Close Cavernize since it's stuck and going no where. Delete the temp .wav file in the chosen folder. Re-launch Cavernize.
4. In the rendering menu, click "Load HRTF/HRIR sets for virtualizer" , pick any of the .wav HRIR files downloaded from the Sadie database (the .sofa format is actually the more common file type for HRTF, which is also provided on the database site, but Cavernize doesn't support it), then Cavernize is frozen for one or two seconds before crashing.

I think there might be something wrong here.

**Comment by VoidXH** [comment]
Fixed in 84e99f8cb830ad91832ddb3cdc0d791641ca807d, build uploaded to Cavern website.
