### ISSUE TITLE
Add support for DBMD

### ISSUE THREAD

**Issue by VoidXH** [VoidXH/Cavern#25]
Requested by @ValZapod. Dolby Atmos Metadata, needed for DME imports. Should be a manual selection as "ADM BWF + DBMD". If all else fails, loading a donor file's DBMD will work.

**Comment by VoidXH** [comment]
Hi @ValZapod, please try to import a file to DME created by the version in c0ac0277aa7df467094cb8eb5a19d9324c42c275.

**Comment by ValZapod** [comment]
The same issue, not authored with Dolby tools.

**Comment by VoidXH** [comment]
What if you change defaultCreationInfo in DolbyMetadata.cs to "Created using Dolby equipment"? That is the original value in DBMDs, but I wanted to try first without it.

**Comment by ValZapod** [comment]
Yes!!! It now fails much later when you start encoding.

![image](https://user-images.githubusercontent.com/31514790/196948164-42a21b34-6006-43b2-a8e6-e9563312bf67.png)


>ERROR: Block format AB_00031010_00000db3 must have rtime plus duration equal to the program duration.

and others.

[log5.txt](https://github.com/VoidXH/Cavern/files/9829982/log5.txt)

**Comment by VoidXH** [comment]
Finally some error messages that actually say something, I can fix these. Thank you! Could you please also try if the defaultCreationInfo is just "Dolby"? I should put a different text there if I can.

**Comment by bluewidy** [comment]
If I change defaultCreationInfo to Created using Dolby equipment or Dolby, I get the following error in both. 
<img width="245" alt="the result" src="https://user-images.githubusercontent.com/40682277/196985154-77fd37b0-7cc9-43a2-91a0-5a1871da0e7c.png">

One thing I found is that the error message displayed by DaVinci Resolve is the same as the error message displayed by the Dolby Atmos Conversion Tool.

**Comment by ValZapod** [comment]
Itndoes not like "Dolby".

**Comment by VoidXH** [comment]
Alright, thanks for trying.

**Comment by VoidXH** [comment]
What about cf3c40fbe015d0f6f62bd82e928823b05237c272?

**Comment by ValZapod** [comment]
This:
![image](https://user-images.githubusercontent.com/31514790/197284117-92dc82b1-af6c-4f96-853d-68a3bbcb82da.png)

**Comment by VoidXH** [comment]
Please try with de71f1dd21e6b6dae35f0b300476b07a0db1cc09. If this doesn't work (all metadata is supported now), please send me a file that does.

**Comment by ValZapod** [comment]
![image](https://user-images.githubusercontent.com/31514790/197303043-b8b092e5-d6d6-4f0e-94bd-27c41dd80b00.png)

This works. https://dolby.app.box.com/s/bart3gfwblydjysegkltoz08wqlvzspg

**Comment by VoidXH** [comment]
Well, there's a little problem, I used exactly this file to create the ADM (de)serializer. This is a bug now, not a missing feature.

**Comment by bluewidy** [comment]
Sir, I also found something.
<img width="917" alt="Dolby Atmos conversion tool errer_message" src="https://user-images.githubusercontent.com/40682277/197317380-ed1af83f-e272-44ab-8104-700e8ba18539.png">

**Comment by bluewidy** [comment]
Thank you, Thank you so much VoidXH! I never thought you would implement this feature in such a short period of time.
DaVinci Resolve no longer cries! It works fantastic XD 
Here's a video https://drive.google.com/file/d/1Lx2ceLH2EzRg4nfPRPkSrhZ3fnjT98MS/view?usp=sharing

**Comment by bluewidy** [comment]
If the audio stream of the EAC3-JOC is too long, it seems to create the master file abnormally. I created an Atmos master file from EAC3-JOC of 2 hours and 2 minutes, and the audio duration of the output master file is 7 minutes and 39 seconds.
<img width="349" alt="something wrong" src="https://user-images.githubusercontent.com/40682277/197323819-1cac7815-c056-45cc-8543-41875e190b46.png">

**Comment by ValZapod** [comment]
https://tech.ebu.ch/docs/tech/tech3285s6.pdf

Looks like thos talks about 24/1.001, 24, others frame rate.

**Comment by VoidXH** [comment]
Found and reverted the commit that broke the framerate. Please build from f9c531dbb1f1556adeee6e29ea1b1c6f28aaa789.

**Comment by bluewidy** [comment]
I have a question every time you post some weird alphabets from time to time. Do I have to build it myself? Or can I just download it here http://cavern.sbence.hu/?

**Comment by VoidXH** [comment]
Yes, you have to build it or change the DLLs to the automatic builds.

**Comment by bluewidy** [comment]
Still getting the same error, sir.
<img width="277" alt="same error" src="https://user-images.githubusercontent.com/40682277/197338516-86393867-e45d-4432-accb-0dffc12be9c3.png">

**Comment by bluewidy** [comment]
> I created an Atmos master file from EAC3-JOC of 2 hours and 2 minutes

I'm researching this issue and I think I've found something... I shredded the two hour and two minute audio stream. No issues when creating a master file with fragments of the audio stream up to 2 minutes. And when I create a master file with fragments of the audio stream from 4 to 6 minutes, no problem. However, when I created a master file from fragments of an audio stream from 2 to 3 minutes, I got this error.

**Comment by bluewidy** [comment]
Here is a sample file for not working timezones. I have succeeded in narrowing the scope with super precision!
https://drive.google.com/file/d/1eGIet8kp0qBYiUYfuaT7RNsD4QaVRv0S/view?usp=sharing

**Comment by VoidXH** [comment]
Found the undocumented location of the timecode. New version released on the site with full DBMD support.

**Comment by ValZapod** [comment]
It works perfectly. OMG. Now people can decode EAC3 and encode TrueHD Atmos. New type of mp3 to CD reencode, haha.

**Comment by bluewidy** [comment]
> Here is a sample file for not working timezones. I have succeeded in narrowing the scope with super precision! https://drive.google.com/file/d/1eGIet8kp0qBYiUYfuaT7RNsD4QaVRv0S/view?usp=sharing
<img width="919" alt="error" src="https://user-images.githubusercontent.com/40682277/197371842-5f2556b1-0592-4c42-9148-f16ac80a614f.png">
But this sample still doesn't work.

**Comment by bluewidy** [comment]
@ValZapod What is your purpose of obtaining ADM BWF files? Maybe... this? > decode EAC3 and encode TrueHD Atmos.
My goal is to output Atmos binaural audio via DaVinci Resolve using an ADM BWF file.

**Comment by bluewidy** [comment]
> But this sample still doesn't work.

You can ignore this message. I've come up with another new alternative. https://github.com/VoidXH/Cavern/issues/40

**Comment by ValZapod** [comment]
>Maybe... this?

Nope, of course not. 😸

**Comment by VoidXH** [comment]
> But this sample still doesn't work.

This was encoded before the fix. Try again.

**Comment by ValZapod** [comment]
>This was encoded before the fix.

That file is eac3. Decoded to ADM it does indeed fail to work on HEAD. The warning is in Dolby Media Encoder is different though, it does not like the amoint of channels. Strange.

**Comment by ValZapod** [comment]
It is possible it does not like that some of the objects do not have automation data. I also tested it on Star wars sample that only has static objects, it warns on the file too.

**Comment by bluewidy** [comment]
> I also tested it on Star wars sample

Oh! Mine is Star trek. We have one thing in common, "Star".

**Comment by ValZapod** [comment]
Importing in Nuendo works, but it says there is no Atmos data and Atmos renderer insert does not work. On my Yello sample it does work.

**Comment by VoidXH** [comment]
Another timing commit, another release on the site. Please try with that.
