### ISSUE TITLE
The sound of activating and listening to the headphone virtualizer sounds very strange.

### ISSUE THREAD

**Issue by bluewidy** [VoidXH/Cavern#26]
Hello, I am an end user who loves Spatial Audio. I enjoy listening to Dolby Atmos or Sony 360 reality audio with my headphones.

I used the very interesting tool you made for the first time today. In your demonstration video, Core Universe's Dolby Atmos sound was fantastic to hear on headphones : https://youtu.be/sZCfmISQdHU

So I've been following you. I downloaded Core Universe(https://thedigitaltheater.com/dolby-trailers/), converted it to mkv using mkvtoolnix, and played it through Cavern.

However, it was very different from the sound I heard through your video. This is the sound I heard through Cavern. (I recorded the output using Audacity.)
https://drive.google.com/file/d/1bJ3tBC3CFs7hgcpd0ROdNI3x9Tpx5WXr/view?usp=sharing

So I was able to activate an option called Headphone Virtualizer, which sounds a lot more strange.
https://drive.google.com/file/d/1dwxo11LPJjwAGxcO0P8ezT_v1kAVf0Iy/view?usp=sharing

How did you set this video when you demonstrated it?

**Comment by VoidXH** [comment]
That video is using the official Dolby Atmos virtualizer which you can get by buying it in Dolby Access. Since it's basically perfect for most users, as Dolby measured more users I ever could, I wouldn't recommend my virtualizer instead of it. Cavern has an open source virtualizer that was made for developers to measure their own ears (just like I did for these samples), and make a personalized one, which can only be better than Atmos if the user who recorded it listens to it.

**Comment by bluewidy** [comment]
> That video is using the official Dolby Atmos virtualizer which you can get by buying it in Dolby Access. Since it's basically perfect for most users, as Dolby measured more subjects than I ever could, I wouldn't recommend my virtualizer instead of it. Cavern has an open source virtualizer that was made for developers to measure their own ears (just like I did for these samples), and make a personalized one, which can only be better than Atmos if the user who recorded it listens to it.

Thank you for the good info. I also have Dolby Access, so I enabled Dolby Access and tried playing through Cavern, but nothing happened. It looks like Cavern and Dolby Access are not interacting, but how did you do it? I am using windows 11.

**Comment by VoidXH** [comment]
> It looks like Cavern and Dolby Access are not interacting

They aren't. It's either Cavern or Dolby, but if you only have headphones, I wouldn't recommend Cavern anyway.

**Comment by ValZapod** [comment]
Cavern driver does not yet the fix for levels, so it is wrong. https://github.com/VoidXH/Cavern/issues/14

**Comment by VoidXH** [comment]
Did you update it? I just tested and it's correct.

**Comment by ValZapod** [comment]
Oh. So it got updated, I did not see that.

**Comment by bluewidy** [comment]
Btw why are you talking here?  Does this mean that the headphone virtualizer has been improved?

**Comment by ValZapod** [comment]
> Btw why are you talking here? Does this mean that the headphone virtualizer has been improved?

No, renderer was improved. -3 db for Downmixing metadata for each of 4 variants.
