### ISSUE TITLE
Buffered reading

### ISSUE THREAD

**Issue by VoidXH** [VoidXH/Cavern#27]
Keep a larger buffer in memory for each stream - maybe with a descendant of BlockBuffer.

**Comment by ValZapod** [comment]
BTW, it is indeed not real time on my 4th gen Intel. Wav playback is real time.

**Comment by VoidXH** [comment]
JOC decoding is very heavy currently, as its DFT is just ever so slightly modified that you can't use FFT on it. This might change as I get into it after fixing bugs.

**Comment by VoidXH** [comment]
Yes. The PCM decoder is about 10% of the total workload, so the real issue is the JOC.

**Comment by ValZapod** [comment]
How does TrueHD decoder work now? Also can you maybe still have an option to use ffmpeg decoder?

**Comment by VoidXH** [comment]
There's no TrueHD decoding currently. I'll prepare it, but until that, I can add a feature to decode any track with FFmpeg.

**Comment by ValZapod** [comment]
Nice.

**Comment by VoidXH** [comment]
Buffering added in f5297d4f8684ca38f2879b9489526959fee2fa89. ADM's bitrate is still so high it only works normally for me on an SSD.

**Comment by ValZapod** [comment]
> There's no TrueHD decoding currently. I'll prepare it, but until that, I can add a feature to decode any track with FFmpeg.

So can you add back TrueHD 24 bit decoding from ffmpeg and changing base layer with that but still using EAC3 metadata? Again, AFAIK, if the number of dynamic objects is the same the streams audio positions are the same, we can verify that with media encoder. But you need to add 256 samples of silence in front of THD track (cause EAC3 encoder delay).

**Comment by VoidXH** [comment]
When that feature was implemented, adding the 256 samples broke it. Priming is still no issue, even ffmpeg is ignoring it.

**Comment by ValZapod** [comment]
>When that feature was implemented, adding the 256 samples broke it.

You need to allign THD samples and EAC3 samples. For that you must add 256 samples to thd decode. Where am I wrong?

**Comment by VoidXH** [comment]
That you don't need this and they're always aligned perfectly. Priming is never used.

**Comment by ValZapod** [comment]
>That you don't need this and they're always aligned perfectly.

THD to wav is not alligned with eac3 to wav. Try with Atmos demo disk, decode eac3 to wav and then thd to wav. You will see that thd wav file is smaller, it does not have 256 silent samples in the start and some small in the end.

**Comment by VoidXH** [comment]
> Try with Atmos demo disk

I did exactly that. They were aligned.

**Comment by VoidXH** [comment]
So there are FFmpeg versions which remove the excess data and some which don't. This would just make the feature even worse.

**Comment by ValZapod** [comment]
Can you at least add back the ability to read the base layer using 0.wav file? Please? So the algorithm is as follows: if CavernizeGUI sees filename0.wav in the ~\ folder it uses that audio instead of EAC3 decode base layer, but applies eac3 metadata. It was very nice before.

I will open the issue.
