### ISSUE TITLE
Report option does not work in CavernizeGUI

### ISSUE THREAD

**Issue by ValZapod** [VoidXH/Cavern#3]
Tested both GUI on your site and compiled with Visual Studio 2022.
[nfdawsdfwa.zip](https://github.com/VoidXH/Cavern/files/9483603/nfdawsdfwa.zip)

**Comment by VoidXH** [comment]
The padding bytes caused a sync exception as there was a 0 in place of the sync word. Will be fixed today.

**Comment by VoidXH** [comment]
Fixed in 9fd0d3fadd591e29dd805032bb93b917f9ae3570

**Comment by ValZapod** [comment]
Fixed: pulled and compiled in Visual Studio 2022! Thanks for such a fast
fix, so cool! :)
