### ISSUE TITLE
Allow the layout set in the Driver in Cavernize GUI

### ISSUE THREAD

**Issue by VoidXH** [VoidXH/Cavern#31]
Don't forget to update the CLI and docs too.

**Comment by VoidXH** [comment]
Implemented in fd11ec8a3b95e74ac667e833048162a563e9e563.

**Comment by kaedewang** [comment]
How to use driver result in gui？
![图片](https://user-images.githubusercontent.com/67850015/213137498-9cec65cd-e54b-4cf0-b621-8e439fb7e2d7.png)

**Comment by VoidXH** [comment]
This is a bug, please follow #66 for the fix.

**Comment by VoidXH** [comment]
That's fixed.

**Comment by kaedewang** [comment]
I don't know how to use. Could you please teach me? 
1.Change the setting in Driver
2.Select Cavern Driver in GUI
3.Render now
Is my step correct?
I find whatever the setting is in Driver, GUI render output is always same.

**Comment by kaedewang** [comment]
And I try to listen in the car to compare the difference. The space is very small. Driver can't set them.

**Comment by VoidXH** [comment]
You have to close the Driver before opening Cavernize to apply the changes.

**Comment by kaedewang** [comment]
I don't understand the angle of w/y and h/x.
Whatever room is square or rectangle, 45 degree is always at corner.
It is very strange.
![图片](https://user-images.githubusercontent.com/67850015/216902861-b388394a-c006-4b07-8450-d6222d5f50b9.png)

**Comment by kaedewang** [comment]
![图片](https://user-images.githubusercontent.com/67850015/216903259-625b23a4-3d69-4cc6-a96e-f847c2a61505.png)

**Comment by VoidXH** [comment]
It's relative to a perfect cube.
