### ISSUE TITLE
REAPER - can not be imported

### ISSUE THREAD

**Issue by troullll** [VoidXH/Cavern#38]
with Ear Production Suite, ADM compact file not recognized, ADM ATMOS file either

**Comment by VoidXH** [comment]
Same as #25, progress is tracked there. Did you try the latest release with file creation dates at 22nd Oct 2022?

**Comment by troullll** [comment]
yes, I used latest files

**Comment by VoidXH** [comment]
New version released, Atmos ADMs are now detected. Compact was not made for Atmos compatibility, that's not a bug.

**Comment by troullll** [comment]
sorry but Atmos still "can not be imported" on Reaper with Ear Production Suite

**Comment by troullll** [comment]
and don't work with Resolve as Import a Master file

**Comment by VoidXH** [comment]
The newest version was reported to work with Resolve. What file did you try?

**Comment by troullll** [comment]
Several, DD+JOC Dolby Demos or Movies, or 7.1 music files...
Neither Reaper nor Résolve

Envoyé de mon iPhone

**Comment by VoidXH** [comment]
Please try replacing the DLLs with [these ones](https://github.com/VoidXH/Cavern/releases/tag/latest).

**Comment by VoidXH** [comment]
New update is also on the website with more ADM BWF fixes.

**Comment by troullll** [comment]
sorry, i'm off and can't try it all this week long 

Envoyé de mon iPhone

**Comment by troullll** [comment]
Still can't import on Reaper, with new DLLs

Envoyé de mon iPhone

Le 25 oct. 2022 à 03:02, Bence Sgánetz ***@***.***> a écrit :



﻿


New update is also on the website with more ADM BWF fixes.

**Comment by troullll** [comment]
Hi, happy new year !Downloaded new EBU production suite on reaper, works with ADM source files, but not with ADM files created by cavernize, sorry

    Le samedi 29 octobre 2022 à 10:46:34 UTC+2, Thomas Roullon ***@***.***> a écrit :  
 
 Still can't import on Reaper, with new DLLs

Envoyé de mon iPhone

Le 25 oct. 2022 à 03:02, Bence Sgánetz ***@***.***> a écrit :



﻿


New update is also on the website with more ADM BWF fixes.

**Comment by VoidXH** [comment]
I have added multiple checks to the ADM Validator, anything I can think of, and it still can't find any issues. Problematic content sometimes work with a time shift (like the Overwatch demo can't be converted, but when you create 3 minute parts, they all work), but this is also inconsistent. I added an AXML export (when saving the file, change the type to XML) for human-readable metadata, but I couldn't find anything wrong with any content. If you could find any issues there, like skipped times, I can fix this, but I wasn't able to locate the issue, Dolby only says the file is invalid, and not why it is invalid.
