### ISSUE TITLE
Open .ec3 files directly in Unity app?

### ISSUE THREAD

**Issue by ValZapod** [VoidXH/Cavern#4]
How does one get this: http://cavern.sbence.hu/cavern/img/home.mp4

**Comment by VoidXH** [comment]
In the current version, add the AC-3 track to an mkv container. To play audio with the visualization, decode the AC-3 to WAV next to it with the same name. Future versions will have decoding capabilities and ac3/ec3 extension support.

**Comment by ValZapod** [comment]
It works, thank you, here is a clip for you showing 01 - Yello - Waba Duba.mkv (01 - Yello - Waba Duba.wav playing and rendering) and all objects playing, so cool! Thanks again! https://photos.app.goo.gl/E8H1rRXUGTfShJ3w7

**Comment by VoidXH** [comment]
Reopened as allowing .ac3 and .ec3 was added to the Driver, but they don't work.

**Comment by VoidXH** [comment]
Fixed in the new version.
