### ISSUE TITLE
Cavernize 1.6 - Incorrect channel mapping.

### ISSUE THREAD

**Issue by bluewidy** [VoidXH/Cavern#42]
https://user-images.githubusercontent.com/40682277/200129173-1e9c5094-f539-47a4-b9ef-1f6cf9046964.mp4

**Comment by VoidXH** [comment]
This is not incorrect. Standard 5.1 is using side speakers, and 5.1 rear can only provide side surround while running both the fronts and rears.

**Comment by bluewidy** [comment]
I see. Then I want to make a feature request.  Is it possible to add a 5.1 rear option to a render target that doesn't play the front?

**Comment by VoidXH** [comment]
It's 5.1 side.

**Comment by bluewidy** [comment]
I already tried the 5.1 side. It definitely doesn't play the front, but there's a problem. The original sound does not place the speakers on the side. It is placed in the rear and at the same time does not play the front speakers.  

 What I don't understand is why the result is playing the rear and front speakers simultaneously. The original does not play both at the same time.

**Comment by VoidXH** [comment]
Because the original is a standard 5.1 side setup. The speakers are angled in 90-110 degrees, which is more side than rear. 5.1 rear puts the surrounds at a 150 degree angle. For movies, only 5.1 side exists, and 5.1 rear was made for early PC games.

**Comment by bluewidy** [comment]
Then, I would like to make a feature request.  Is it possible to add a 5.1 side tilted 90-110 degrees to the render target?

**Comment by VoidXH** [comment]
You have an option for it, but I don't recommend it. To do this, open the Cavern Driver, set it to 5.1 surround (it's exactly the angles you want), and set Cavernize to Cavern Driver. It will break the sound, as the files don't conform internally to this layout. All files use the corners and side centers of the room, you can see this by loading Atmos content in Cavern Driver. Dolby is using 45/90 degrees instead of 20-30/90-110, as it's way easier to work with in the renderer. All AVRs also render this way. When Cavernize loads the files, it will put them at Dolby's locations (in the front corners and side centers), to achieve spatial equivalence with Atmos. It will only sound the same as the input, if you use 5.1 side for 5.1 content, and this is correct by standard.

**Comment by bluewidy** [comment]
Ah... I see. I thought of another alternative. I'll just use ffmpeg to perform 5.1 pcm encoding. This gives the same angle as the original.

**Comment by VoidXH** [comment]
FFmpeg works exactly the same way if you set Cavernize to 5.1 side.

**Comment by bluewidy** [comment]
> Both result in the same output.

It's not the same. 

https://user-images.githubusercontent.com/40682277/200133539-ce01fe4d-c5b6-4e16-9d70-71dca0fcfb16.mp4

**Comment by VoidXH** [comment]
Compare it with 5.1 side, not 5.1 rear.

**Comment by bluewidy** [comment]
Oh, I'm sorry. I missed the need to extract to the 5.1 side, not the 5.1 rear. As you said, the two are identical. 
But what I am curious about is that the alphabet has changed.
BL -> SL 
BR -> SR
https://user-images.githubusercontent.com/40682277/200134026-b4be999f-1d52-4281-a2dd-05a28b81c0bc.mp4

**Comment by bluewidy** [comment]
Wait... BL and BR are 5.1 rears. Right? Then, as you can see from the video, FFMPEG creates 5.1 rear and does not play front speakers. On the other hand, the 5.1 rear created through Cavernize is playing the front speakers together.

**Comment by VoidXH** [comment]
FFmpeg creates unmarked 5.1 files as default. It's up to the player what to write in this case, but the correct is side.

**Comment by bluewidy** [comment]
I see. Thank you for always sharing your knowledge.

**Comment by bluewidy** [comment]
<img width="644" alt="Original 5 1 track" src="https://user-images.githubusercontent.com/40682277/200154425-90e8d2b5-bb22-458b-b8fb-ee00c40a6829.png">

By the way, I missed the crux of my question yesterday, why does the 5.1 rear created by Cabanize play both the front and rear speakers at the same time? Take a look at my waveform picture. There is no timeline with front and rear speaker tracks coexisting. 

and According to the ffmpeg wiki, ffmpeg defaults to 5.1 rear for 5.1 channel layout. If I want a 5.1 side I have to explicitly use a parameter for the layout. and as you can see, they do not use the front and rear speakers at the same time.
https://drive.google.com/file/d/1TJT9WdL_T0JGPsWb_M99sFyc8b6Sqi2X/view?usp=sharing

**Comment by ValZapod** [comment]
>FFmpeg has no default layout in case of WAV, it just copies the channels, but if the order is not correct, it swaps them around.

Unless there is a bug. Like we recently fixed Sony's ATRAC3 (LDAC in Android 9 [is ATRAC9](https://github.com/hegdi/libldacdec), LOL): https://github.com/FFmpeg/FFmpeg/commit/3819719099df601c470e961b9d49b9100c65641b

And even 48 channels aac works now: https://github.com/FFmpeg/FFmpeg/commit/ced6a5affb0ab1a24278b9bade76c36b8636e267
(sample is here: https://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_IEC_14496-26_2010_Bitstreams/DVD1/mpeg4audio-conformance/compressedMp4/al08_44.mp4)

**Comment by bluewidy** [comment]
> we recently fixed

You used the expression 'we'. Are you one of the people involved in the development of ffmpeg?

**Comment by ValZapod** [comment]
Sure. https://github.com/FFmpeg/FFmpeg/commits?author=ValZapod

**Comment by bluewidy** [comment]
Nice! Nice to meet you, developer. I have a matter to report to you. This is something I recently posted on the ffmpeg bug tracker. Could you please take a look at this?
https://trac.ffmpeg.org/ticket/9996

**Comment by ValZapod** [comment]
I am the one who opened that issue. I knew about it for some time

**Comment by bluewidy** [comment]
Oops... I never imagined he would be you 😆
