### ISSUE TITLE
Is it possible to play atmos file without convert

### ISSUE THREAD

**Issue by kaedewang** [VoidXH/Cavern#44]
Now i can play convert file by jriver. The player uses asio in windows to output more than 8ch audio.
Can Cavern be used as audio decoder plugin in player to play atmos file directly?

**Comment by VoidXH** [comment]
Not yet, see #15.

**Comment by bluewidy** [comment]
wow... This is an incredibly interesting topic! If this is realized, it will be possible to decode Dolby Atmos by inserting the Atmos decoder plug-in in PotPlayer?!
