### ISSUE TITLE
feature request: Please consider adding QuickEQ export for CamillaDSP

### ISSUE THREAD

**Issue by thinkbig1979** [VoidXH/Cavern#45]
CamillaDSP supports many of the features of Equalizer APO, but is cross platform and open source. Being able to export to CamillaDSP would enable very powerful DSP on low power SBCs and in many situations where using a Windows PC is not an option.

**Comment by VoidXH** [comment]
Convolution exports can already be used in any DSP supporting FIR filters. Please provide a sample configuration file for importing those WAV files and I will add this feature.

**Comment by thinkbig1979** [comment]
Great!
The config format for filters is very well documented here:
https://github.com/HEnquist/camilladsp#filters

There is also a repo with example configs for various things, this may be of use as well:
https://github.com/HEnquist/camilladsp-config

**Comment by VoidXH** [comment]
Thanks, this will help. I also found a [full sample here](https://github.com/HEnquist/camilladsp/blob/7cdc687cf0639433cdeab7f0cb308f9856bd99fc/exampleconfigs/simpleconfig_plot.yml).

**Comment by VoidXH** [comment]
Done in 230f0f170ede41df9ae55e1fbb4112848fd40705, released.
