### ISSUE TITLE
macOS port?

### ISSUE THREAD

**Issue by sclsj** [VoidXH/Cavern#46]
I would like to do advanced playback and decoding of Dolby Atmos e-ac-3 on macOS, and it seems like this is the only software that supports it. However, it seems like this only runs on Windows and does not work under wine. Is porting this to macOS an easy job or should I plan on purchasing Parallels Desktop to run this inside a Windows VM?

**Comment by VoidXH** [comment]
While I don't make Mac builds because I don't have a Mac, since the software is open source, you can make it yourself by downloading Visual Studio (which is free for open source projects).

**Comment by sclsj** [comment]
So I downloaded Visual Studio and clicked on the run/build icon. What do I do next?

**Comment by sclsj** [comment]
There are bin folders in the subfolders of cavern (github download), but they seems to contain xml and dll, none of which is a mac application / executable.

**Comment by sclsj** [comment]
I'm trying to build both Cavernize and Cavern Driver.

**Comment by VoidXH** [comment]
Just set it up this way, press Run (play icon), and it will launch:
![image](https://user-images.githubusercontent.com/7473142/209886747-71f4e465-2136-400c-9e6b-e78d368996a6.png)

The Driver's front-end is closed source (OTS licences don't let me open sourcing it), so you can only launch it from a virtual Windows.

**Comment by sclsj** [comment]
This is what I see when I open Cavern.sln:

<img width="1642" alt="截屏2022-12-29 10 48 49" src="https://user-images.githubusercontent.com/38654636/209896957-d85beb64-017e-4496-8719-02b079602a3e.png">

I can't find anything related to CaverniseGUI. Maybe I'm not familiar with VS and it's in a hidden menu / thing.

I did find `Cavern/CavernSamples/CavernizeGUI`, but when I open CavernizeGUI.sln it does not allow me to build.

<img width="1642" alt="截屏2022-12-29 10 54 39" src="https://user-images.githubusercontent.com/38654636/209897419-c1eccf63-6a12-4b99-be7a-d47fa01765aa.png">

<img width="1652" alt="截屏2022-12-29 10 54 42" src="https://user-images.githubusercontent.com/38654636/209897435-ba905c30-cac1-47dc-9b61-514fd77bd147.png">

**Comment by sclsj** [comment]
So I tried random commands online to see if they will work.

1. 
```
> /usr/local/share/dotnet/dotnet msbuild /Users/jin/cavern1/CavernSamples/CavernizeGUI/CavernizeGUI.csproj
/usr/local/share/dotnet/sdk/7.0.101/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(90,5): error NETSDK1100: 若要在此操作系统上生成面向 Windows 的项目，请将 EnableWindowsTargeting 属性设置为 true。 [/Users/jin/cavern1/CavernSamples/CavernizeGUI/CavernizeGUI.csproj]
```
Following online tutorials I added `<EnableWindowsTargeting>true</EnableWindowsTargeting>` to the .csproj file.

2. Run that again. 
```
/usr/local/share/dotnet/sdk/7.0.101/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(267,5): error NETSDK1004: 找不到资产文件“/Users/jin/cavern1/CavernSamples/CavernizeGUI/obj/project.assets.json”。运行 NuGet 包还原以生成此文件。 [/Users/jin/cavern1/CavernSamples/CavernizeGUI/CavernizeGUI.csproj]
```
3.  
```
nuget restore /Users/jin/cavern1/CavernSamples/CavernizeGUI/CavernizeGUI.sln -o packages
MSBuild auto-detection: using msbuild version '' from '/opt/homebrew/bin'.

>>>> xbuild tool is deprecated and will be removed in future updates, use msbuild instead <<<<

MSBUILD: error MSBUILD0004: Too many project files specified
```
4. 
```
/usr/local/share/dotnet/dotnet msbuild -t:restore Cavern.sln
MSBuild version 17.4.0+18d5aef85 for .NET
  正在确定要还原的项目…
  已还原 /Users/jin/cavern1/Cavern.QuickEQ/Cavern.QuickEQ.csproj (用时 34 ms)。
  已还原 /Users/jin/cavern1/Cavern.Format/Cavern.Format.csproj (用时 34 ms)。
  1 个项目(共 3 个)是最新的，无法还原。
```
```
/usr/local/share/dotnet/dotnet restore CavernizeGUI.csproj 
  正在确定要还原的项目…
  已还原 /Users/jin/cavern1/CavernSamples/CavernizeGUI/CavernizeGUI.csproj (用时 2.96 sec)。
  2 个项目(共 3 个)是最新的，无法还原。
```
```
/usr/local/share/dotnet/dotnet msbuild CavernizeGUI.csproj
MSBuild version 17.4.0+18d5aef85 for .NET
  Cavern -> /Users/jin/cavern1/Cavern/bin/Debug/netstandard2.1/Cavern.dll
  cp: ..CavernAmpbinReleaseCavernAmp.dll: No such file or directory
  Cavern.Format -> /Users/jin/cavern1/Cavern.Format/bin/Debug/netstandard2.1/Cavern.Format.dll
  cp: ..CavernAmpbinReleaseCavernAmp.dll: No such file or directory
  CavernizeGUI -> /Users/jin/cavern1/CavernSamples/CavernizeGUI/bin/Debug/net6.0-windows/CavernizeGUI.dll
```
```
/usr/local/share/dotnet/dotnet /Users/jin/cavern1/CavernSamples/CavernizeGUI/bin/Debug/net6.0-windows/CavernizeGUI.dll
You must install or update .NET to run this application.

App: /Users/jin/cavern1/CavernSamples/CavernizeGUI/bin/Debug/net6.0-windows/CavernizeGUI.dll
Architecture: arm64
Framework: 'Microsoft.WindowsDesktop.App', version '6.0.0' (arm64)
.NET location: /usr/local/share/dotnet/

No frameworks were found.

Learn about framework resolution:
https://aka.ms/dotnet/app-launch-failed

To install missing framework, download:
https://aka.ms/dotnet-core-applaunch?framework=Microsoft.WindowsDesktop.App&framework_version=6.0.0&arch=arm64&rid=osx.12-arm64
```
> /usr/local/share/dotnet/dotnet publish CavernizeGUI.csproj -c Release -o cavern_publish --runtime osx.12-arm64
MSBuild version 17.4.0+18d5aef85 for .NET
  正在确定要还原的项目…
  已还原 /Users/jin/cavern1/Cavern.Format/Cavern.Format.csproj (用时 51 ms)。
  已还原 /Users/jin/cavern1/Cavern/Cavern.csproj (用时 51 ms)。
  已还原 /Users/jin/cavern1/CavernSamples/CavernizeGUI/CavernizeGUI.csproj (用时 4.82 sec)。
/usr/local/share/dotnet/sdk/7.0.101/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(1136,5): warning NETSDK1179: 使用“--runtime”时，必需选择“--self-contained”或“--no-self-contained”选项。 [/Users/jin/cavern1/CavernSamples/CavernizeGUI/CavernizeGUI.csproj]
/usr/local/share/dotnet/sdk/7.0.101/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(448,5): error NETSDK1082: Microsoft.WindowsDesktop.App 没有运行时包可用于指定的 RuntimeIdentifier“osx.12-arm64”。 [/Users/jin/cavern1/CavernSamples/CavernizeGUI/CavernizeGUI.csproj]
```
```
/usr/local/share/dotnet/dotnet publish CavernizeGUI.csproj -c Release -o cavern_publish --no-self-contained --runtime osx.12-arm64
MSBuild version 17.4.0+18d5aef85 for .NET
  正在确定要还原的项目…
  已还原 /Users/jin/cavern1/CavernSamples/CavernizeGUI/CavernizeGUI.csproj (用时 60 ms)。
  2 个项目(共 3 个)是最新的，无法还原。
  Cavern -> /Users/jin/cavern1/Cavern/bin/Release/netstandard2.1/Cavern.dll
  cp: ..CavernAmpbinReleaseCavernAmp.dll: No such file or directory
/Users/jin/cavern1/Cavern.Format/Transcoders/EnhancedAC3Body/Memory.cs(84,13): warning CS0649: 从未对字段“EnhancedAC3Body.cplahtinu”赋值，字段将一直保持其默认值 0 [/Users/jin/cavern1/Cavern.Format/Cavern.Format.csproj]
/Users/jin/cavern1/Cavern.Format/Transcoders/EnhancedAC3Body/Memory.cs(106,13): warning CS0649: 从未对字段“EnhancedAC3Body.lfeahtinu”赋值，字段将一直保持其默认值 0 [/Users/jin/cavern1/Cavern.Format/Cavern.Format.csproj]
  Cavern.Format -> /Users/jin/cavern1/Cavern.Format/bin/Release/netstandard2.1/Cavern.Format.dll
  cp: ..CavernAmpbinReleaseCavernAmp.dll: No such file or directory
  CavernizeGUI -> /Users/jin/cavern1/CavernSamples/CavernizeGUI/bin/Release/net6.0-windows/osx.12-arm64/CavernizeGUI.dll
  CavernizeGUI -> /Users/jin/cavern1/CavernSamples/CavernizeGUI/cavern_publish/
```
```
> /Users/jin/cavern1/CavernSamples/CavernizeGUI/cavern_publish/CavernizeGUI
You must install or update .NET to run this application.

App: /Users/jin/cavern1/CavernSamples/CavernizeGUI/cavern_publish/CavernizeGUI
Architecture: arm64
Framework: 'Microsoft.WindowsDesktop.App', version '6.0.0' (arm64)
.NET location: /usr/local/share/dotnet

No frameworks were found.

Learn about framework resolution:
https://aka.ms/dotnet/app-launch-failed

To install missing framework, download:
https://aka.ms/dotnet-core-applaunch?framework=Microsoft.WindowsDesktop.App&framework_version=6.0.0&arch=arm64&rid=osx.12-arm64
```

**Comment by sclsj** [comment]
The main reason I'm trying to get these to work in macOS is because it's really really slow on Windows. I'm using m1 max, macOS 12, Parallels for virtualization, and Windows 11 for ARM. I cannot play audio files at normal speeds in Cavern. I(Currently the audio plays at 0.5x with a huge amount of stutter; it sounds like holding the space bar on an application that was playing music).
If I can't get this to work on mac, is there anyway to speed those up on Windows? I'm thinking of compiling for arm which may help, but it seems like the exe I produce is still x86. This is the command I used.
```
/usr/local/share/dotnet/dotnet publish CavernizeGUI.csproj -c Release -o cavern_publish_win --no-self-contained --runtime win10-arm64
```

**Comment by VoidXH** [comment]
Change the Debug preset to Release and you get proper performance. It should be about 5x real-time on the M1 Max.

**Comment by sclsj** [comment]
I see. 

However, I'm still having trouble compiling cavernGUI for macOS. If you can take a look at 7-9?

**Comment by VoidXH** [comment]
Yeah, WPF support is completely absent from Mac OS, not just on the runtime level. Sorry, it can only run on Windows.

**Comment by sclsj** [comment]
I actually also tried running the Windows binary (cavernizeGUI) with wine, but it does not show any output / GUI for ~ 1 hour and a constant CPU usage of 100%.

**Comment by VoidXH** [comment]
If you run it in Debug mode from Visual Studio and press pause while the bug is happening, it will show you the exact line of code causing this behavior.

**Comment by sclsj** [comment]
Unfortunately I don't think Visual Studio works under wine. I'm using wine under macOS, so I'm essentially still trying to run cavernizeGUI on macOS.

**Comment by VoidXH** [comment]
I don't think it will run without proper virtualization.
