### ISSUE TITLE
Cavernize GUI compatibility issue on Windows 11 22H2.

### ISSUE THREAD

**Issue by bluewidy** [VoidXH/Cavern#48]
Cavernize GUI is not compatible with Windows 11 22H2 version. The ADM BWF conversion process always behaves erratically and does not result in desirable interactions with respect to any software that inserts the Dolby Atmos Master.

**Comment by VoidXH** [comment]
Does converting the same file with the latest release works correctly on Windows 10?

**Comment by bluewidy** [comment]
I've never used the Cavernize GUI on Windows 10. I think I should summon @Valzapod. Maybe he's Windows 10.

**Comment by VoidXH** [comment]
Can you show a conversion result that doesn't match the result when it was run on a previous Windows version?

**Comment by bluewidy** [comment]
I've already shown it several times in conversations with ValZapod.
https://github.com/VoidXH/Cavern/issues/28#issuecomment-1312487158

**Comment by VoidXH** [comment]
And that's only on Windows 11 22H2 and works perfectly in 21H2?

**Comment by bluewidy** [comment]
Yup.

**Comment by ValZapod** [comment]
I am on 11 22H2 too. Of course.

**Comment by bluewidy** [comment]
That's a bit embarrassing... 3DJ on 22H2 was also in the same situation as me, so I inferred that it was an OS compatibility issue.

**Comment by ValZapod** [comment]
Can we reopen this? I mean the bug is real, this is reproducability issue. I can reproduce on Windowd 10 but not on 11 22H2 and for me 22H2 works correctly.

**Comment by VoidXH** [comment]
That's a halted bug about the ADM BWF converter itself. Yes, it has a platform-dependent behavior, but both are bad in some cases, so the ADM encoder is the problem, not Windows. A good algorithm should work with all kinds of roundings, and small rounding errors are not an issue. Until the actual checks Dolby performs are known, or at least error messages, I can't continue working on this.

**Comment by ValZapod** [comment]
>Yes, it has a platform-dependent behavior

Which is a bug in by itself.

>but both are bad in some cases,

You do not have access to my PC and my files to say so.

>A good algorithm should work with all kinds of roundings, and small rounding errors are not an issue

That is clearly false, since before interpolation changes it still worked for me.

>Until the actual checks Dolby performs are known, or at least error messages, I can't continue working on this.

I gave you xmls.

**Comment by VoidXH** [comment]
> Which is a bug in by itself.

A bug of the CLR. There are many of these I can't do anything about, like the sporadically missing .NET 6 installation detection.

> You do not have access to my PC and my files to say so.

You uploaded your AXMLs.

> That is clearly false, since before interpolation changes it still worked for me.

Interpolation was always there. Did you try Core Universe?

> I gave you xmls.

Even having the original wouldn't help if we don't know what to look for.

**Comment by ValZapod** [comment]
So, this is bug in CLR, lets concentrate on that. First of all my static C# analyzer has some warnings on naive float manipulation: 

https://github.com/VoidXH/Cavern/blob/46295a070aa8e7cd0d72b614eb032851efa1d06e/Cavern.Format/Decoders/EnhancedAC3/JointObjectCodingDecoder.cs#L137

This has highest warning: The expression was implicitly cast from 'int' type to 'float' type. Consider utilizing an explicit type cast to avoid the loss of a fractional part. An example: double A = (double)(X) / Y;. Indeed, you need double precision inside / operation and then you should use double too. This can be the issue. 

Here are all warnings: 
[CavernSamples33.txt](https://github.com/VoidXH/Cavern/files/10527707/CavernSamples33.txt)

**Comment by VoidXH** [comment]
This is a very good finding, and does fix an awful lot of distortions. Fix coming soon.

**Comment by ValZapod** [comment]
> This is a very good finding, and does fix an awful lot of distortions. Fix coming soon. Since small ints have 1:1 mapping to float, doubles are not needed, the fix still works with minimal memory use and optimal sample manipulation performance.

The fact is there is no difference on my PC. That is because here CLR bug is fixed (?). I am not bisecting the .Net components though.

Please revert all interpolation commits (b3a6049d9cade7d36e2975709ff6e8e9744109f9, cause Core Universe problem, 7d7c5321a14b0f953a98e568138980494dea3453, 4217afd69bb1dfe644591657028523b1d6ce7a3b) and maybe please update to windows 11?

I still do not get where did you find that Dolby tools only support 

>The only allowed Atmos jump time is 0 or this

Cause ADM spec must be followed, not Dolby's idea of it, and BTW, there are no known decoders for Atmos EAC3 to ADM, so how do you know? Did you dissasemble the binaries?

**Comment by VoidXH** [comment]
> how do you know?

Look at any output from those encoders.

> Please revert all interpolation commits

After more investigation it might happen.

**Comment by ValZapod** [comment]
> > how do you know?
> 
> Look at any output from those encoders.
> 
> > Please revert all interpolation commits
> 
> After more investigation it might happen.

https://github.com/VoidXH/Cavern/commit/b3a6049d9cade7d36e2975709ff6e8e9744109f9 cause a bug in core universe on my good PC. I bisected it. It must be reverted.

**Comment by ValZapod** [comment]
>Look at any output from those encoders.

You only have DACT, that is not an encoder, it does not even preserve stuff. It has no analyser. Dolby Media Enocder does. The fact is old good interpolations work well here in DACT, Dolby Media Encoder, etc. In fact the files are mostly bitperfect, which is strange, right? But still.

**Comment by VoidXH** [comment]
> You only have DACT

And lots of master content, all of which have the same exact value everywhere.

**Comment by bluewidy** [comment]
> does fix an awful lot of distortions

Oh, is that news for me to rejoice?

**Comment by VoidXH** [comment]
> Oh, is that news for me to rejoice?

No, the code that's wrong in the standard is still wrong and most likely always will be.

**Comment by ValZapod** [comment]
And BTW, 

>Not working timeline sample.eac3

also broke with (will check)
https://github.com/VoidXH/Cavern/commit/b3a6049d9cade7d36e2975709ff6e8e9744109f9

**Comment by VoidXH** [comment]
Reverting that commit is not a universal solution as it only fixes one content for one user, and the commit decreased file sizes by a lot. Reverting a perfectly fine safeguard does not help you get closer to what is the root cause for unsupported ADMs. The problem could be too large object movements, invalid positions, anything. Unless we narrow it down for a specific AXML property and not specific commits for specific content, there is no way to universally advance the ADM encoder.

**Comment by ValZapod** [comment]
And that also broke dolby-test-tones_7_1_4.mp4, I cannot even test it -3 dB commit.

>and the commit decreased file sizes by a lot.

It increased them by 170 MB.

>there is no way to universally advance the ADM encoder.

You can just update to Windows 11 22H2.

**Comment by bluewidy** [comment]
yeah... That's a good idea.  Join us on Windows 11 22h2, Sir.

**Comment by ValZapod** [comment]
And, BTW, I proposed a solution: add b3a6049d9cade7d36e2975709ff6e8e9744109f9, 7d7c5321a14b0f953a98e568138980494dea3453, 4217afd69bb1dfe644591657028523b1d6ce7a3b

inside another option in drop down menu. Default without those commits.

**Comment by ValZapod** [comment]
>And lots of master content, all of which have the same exact value everywhere.

maybe that is just what Pro tools by apple does, remember Nuendo requires 512 samples inside ASIO4ALL v2, which is a very strange limitation since https://github.com/dechamps/FlexASIO allows for smaller value in very fast PCs.

**Comment by ValZapod** [comment]
What do you mean by destortions? in XML? Or audio?

Cause audio is different now.

**Comment by VoidXH** [comment]
> I cannot even test -3 dB commit

I already tested and it fixes the clippings. You can check it by looking at any channel-based render.

> It increased them (iXML) by 170 MB.

Depends on the case. For very long interpolations, yes, it exports multiple values, but generally increased the 64 sample entry intervals to 768, making less entries neccessary for complex movements.

> You can just update to Windows 11 22H2.

It's like saying if your kid has issues at school, just make a new one.

> And, BTW, I proposed a solution

We want a correct solution, not patches upon patches which might work but have to be manually tried by the user on every occasion. That's the worst user experience possible. We need to know why it is bad to even start working on it. Pointing at random features which fix some content but break others is not going to work, and would be completely reverted when the fix arrives anyway. We need a root cause, and unless there is an actual valid root cause, not in the code, but in Dolby's ADM interpretation (which very much differs from the real ADM), there is no good path.

> maybe that is just what Pro tools by apple does

There is a reason for all encoding software doing this.

> Cause audio is different now.

Yes, it's -3 dB.

**Comment by ValZapod** [comment]
>Yes, it's -3 dB.

No, it is not, we are talking ADM here, it is the same after -3dB fix. Difference in ADM happened after fcd27df320629ac67371e13eae45687f911cadbb.

**Comment by ValZapod** [comment]
>It's like saying if your kid has issues at school, just make a new one.

Which is precisly what happens when I update gcc or clang/glibc when I code in C/C++ or even compile gcc with gcc to test the trunk. Just recently: https://github.com/Beep6581/RawTherapee/issues/6384

In this case parts of compiler are part of windows and so windows must be updated.

**Comment by VoidXH** [comment]
> Difference in ADM happened after [fcd27df](https://github.com/VoidXH/Cavern/commit/fcd27df320629ac67371e13eae45687f911cadbb).

That's the band interpolation fix. It's expected.

> In this case parts of compiler are part of windows and so windows must be updated.

The "compiler" is the CLR, and it's part of a native package, not Windows. If our versions and CPU features are the same, we run the same exact machine code.

**Comment by ValZapod** [comment]
>The "compiler" is the CLR, and it's part of a native package, not Windows

It is more simple to update windows, takes 30 minutes on my nvme drive, compared to compiling new standard library and bootstraping Roslin, cause Roslin is written in C# and to compile C# you need a C# compiler.

>Depends on the case. For very long interpolations, yes, it exports multiple values, but generally increased the 64 sample entry intervals to 768, making less entries neccessary for complex movements.

And it also broke media encoder (which YOU do not have, right, so you do not even test the most important utility and work blind) and it also increased 3.5 MB ADM to 4.1 MB, which is attached in https://github.com/VoidXH/Cavern/issues/74#issuecomment-1407475107

**Comment by VoidXH** [comment]
> It is more simple to update windows

I'd prefer if the software worked on every supported OS, which would be the case if we'd known what tests are done by the Dolby parser. Speaking of which:

> you do not even test the most important utility

Every Atmos ADM BWF importer is using the same exact code with the same exact error message. DACT is a perfectly viable test tool.
