### ISSUE TITLE
always output 16bit wav

### ISSUE THREAD

**Issue by kaedewang** [VoidXH/Cavern#51]
Is it possible to output 24bit wav or 32bit wav by the following modify？
    writer = new RIFFWaveWriter(exportName, activeRenderTarget.Channels,
                        target.Length, listener.SampleRate, BitDepth.Int24);//wj2 Int16);
                } else {
                    writer = AudioWriter.Create(exportName, activeRenderTarget.Channels.Length,
                        target.Length, listener.SampleRate, BitDepth.Int24);//wj2 Int16);
![图片](https://user-images.githubusercontent.com/67850015/209300399-a4719307-f3dd-4911-a89a-118093c48a26.png)

**Comment by VoidXH** [comment]
Yes, this modification results in what you want. Int32 is not supported, but you could easily change the multiplier and word length in RIFFWaveAudioWriter.

**Comment by ValZapod** [comment]
Do you want 32 bit float or 32 bit integer? Cause 32 bit integer is very obscure. FFmpeg does added 32 bit flac though...

**Comment by kaedewang** [comment]
32 bit is useless. My system only supports 24bits.

**Comment by VoidXH** [comment]
24 bit is now added as a special option in the Render menu.
