### ISSUE TITLE
Cavern for Unity build under macOS

### ISSUE THREAD

**Issue by sclsj** [VoidXH/Cavern#52]
1. Installed Unity.
2. Replaced reference in .csproj with `/Applications/Unity/Unity.app/Contents/Managed/UnityEngine.dll` and `/Applications/Unity/Unity.app/Contents/Managed/UnityEditor.dll`
3. Run

Result
```
/Users/jin/cavern1/CavernUnity DLL/AudioListener3D.cs(31,31): Error CS1501: No overload for method 'Normalize' takes 4 arguments (CS1501) (CavernUnity DLL)
```
I have no experience with C# or Unity so I have no idea if I'm doing anything wrong.

**Comment by sclsj** [comment]
<img width="1642" alt="截屏2022-12-29 15 54 37" src="https://user-images.githubusercontent.com/38654636/209920825-62cdeb9b-64b1-44d7-899a-9c1b7f9837a5.png">

**Comment by sclsj** [comment]
It seems like there is arm version of Unity for macOS but not for Windows?

**Comment by sclsj** [comment]
I also tried the same steps under Windows but failed with the same error.

**Comment by sclsj** [comment]
So I tried with the 1.6 release, and it seemed to work. However, like with cavern I still got a bunch of dlls instead of a mach exec. Trying to run them with dotnet results in similar errors: (can't figure out how to get the output in English)

```
> /usr/local/share/dotnet/dotnet run
无法运行项目。
请确保你具有可运行的项目类型且“dotnet run”支持此项目。
可运行的项目应面向可运行的 TFM (例如 net5.0)且其 OutputType 为 "Exe"。
当前的 OutputType 为“Library”。
```
```
> /usr/local/share/dotnet/dotnet /Users/jin/Downloads/Cavern-1.6/CavernUnity\ DLL/cavern_unity_macos/Cavern.dll
A fatal error was encountered. The library 'libhostpolicy.dylib' required to execute the application was not found in '/Users/jin/Downloads/Cavern-1.6/CavernUnity DLL/cavern_unity_macos/'.
Failed to run as a self-contained app.
  - The application was run as a self-contained app because '/Users/jin/Downloads/Cavern-1.6/CavernUnity DLL/cavern_unity_macos/Cavern.runtimeconfig.json' was not found.
  - If this should be a framework-dependent app, add the '/Users/jin/Downloads/Cavern-1.6/CavernUnity DLL/cavern_unity_macos/Cavern.runtimeconfig.json' file and specify the appropriate framework.
```

**Comment by sclsj** [comment]
Same thing with Windows.

**Comment by sclsj** [comment]
If I change it from library to windows app, it gave me error CS5001. Am I understanding correct that this "cavernunity dll" project is the same as the Cavern Driver?

**Comment by VoidXH** [comment]
CavernUnity DLL is a library, a software development tool, not the driver. Thank you for the bug report, it's tracked in #54. Cavern is not released for Mac for three reasons:
1. Macs already have its functionality for decoding
2. Performance is reportedly sufficient in Parallels on x64 Windows
3. Keeping the release cycle would require heavy investment (buying a Mac)
