### ISSUE TITLE
768 initial samples of silence (256*3) should be removed and remainder too

### ISSUE THREAD

**Issue by ValZapod** [VoidXH/Cavern#6]
To make it truely gapless initial priming (256 samples or 768 samples or 1792) and end priming (called remainder) should be removed from all channels. ec3 does not have such metadata, this is only mp4 feature.

**Comment by VoidXH** [comment]
Sorry, I don't understand this issue. Cavern doesn't even have MP4 support.

**Comment by ZaquL** [comment]
When encoding with dolby media encoder (dolby reference player, whatever) it always inserts 768 samples (each frame in eac3 has) 256 samples are just silence. So those should never be played. That is called encoder delay, or priming. Same in AAC.

**Comment by VoidXH** [comment]
I see, ETSI TS 102 366 V1.4.1 J.1.3.2 provides sufficient information, and my testing also shows that the resulting audio is delayed by 512 samples in addition to the 64 samples of QMFB delay. However, FFmpeg also delays the image, so sync is not broken. FFmpeg also appears to disregard the priming in WAV exports. What would be the issue this behaviour is causing?

**Comment by ValZapod** [comment]
> FFmpeg also appears to disregard the priming in WAV exports.

It does not when encoded in its own eac3 encoder into mp4 file. ETSI spec says you need to write priming in mp4 editlist, media time for initial priming and media duration to remove possible stuff in the end. Mkv priming is on patchwork, yes, as of 3 days ago. FFmpeg always has 256 priming.

Are you sure it is 512 samples? Dolby encoders shpuld be 768...

What I am afraid about is whether there may be some gotchas in the Atmos spec that will desync everything because of priming.

**Comment by VoidXH** [comment]
I did the test with a Dolby demo, and by comparing the original audio and the result's audio (both decoded by FFmpeg), the delay was 512 + 64 samples.

Offsetting even one audio frame completely brakes the audio, +/- 64 samples however are fine. The frame alignment looks the same as for FFmpeg, there's most likely something else that it adds to the container. I would just bypass any video and auxillary information while handling the transcoding, this way priming stays if it existed, and not when it didn't (e.g. cut content).

**Comment by VoidXH** [comment]
Closing this as multiple tests show that priming is handled by the container.

**Comment by ValZapod** [comment]
BTW, i tested lakd Dolby Meia encoder, it also does not write priming in editlist of mp4. Sigh. Dolby, dolby...
