### ISSUE TITLE
[Feature request] Atmos passthrough

### ISSUE THREAD

**Issue by ThreeDeeJay** [VoidXH/Cavern#61]
I always wanted to be able to passthrough/bitstream the Atmos track out of common players like VLC, MPC-HC/BE, PotPlayer, Kodi and into a Dolby Atmos spatializer software for headphones so that instead of just the core/multichannel mix, we hear proper 3D audio from Atmos tracks in content like Blu-ray discs/rips, streaming services with apps/addons capable of Atmos passthrough ([Tidal](https://github.com/arnesongit/plugin.audio.tidal2/blob/26f33be788aaa46943001cd4ebaf80321320b391/changelog.txt#L13), [Netflix](https://github.com/CastagnaIT/plugin.video.netflix/blob/1bc0ede1a20137d350239a57375385c873cf2a2e/README.md?plain=1#L25), [HBO Max](https://github.com/matthuisman/slyguy.addons/blob/master/slyguy.hbo.max/resources/lib/plugin.py#L550), [Paramount+](https://github.com/matthuisman/slyguy.addons/blob/c3a8ce43a3ec88c4599d45bdcbfc66e4ad5d905c/slyguy.paramount.plus/resources/lib/plugin.py#L702)).
I'm not completely sure if/how this would work, but perhaps Cavern could try intercepting the passthrough (perhaps via WASAPI loopback?) from a playback device (AVR, sound card, etc) or use a passthrough-capable virtual audio device to decode and spatialize Atmos (hopefully in realtime/with minimal delay).
Any idea if this would be feasible? 🤔

**Comment by ValZapod** [comment]
MPC-HC already has best implementation in Lavfilter of bitstreaming Atmos. Much better than ffmpeg does.

**Comment by VoidXH** [comment]
This is already a feature in Windows, Dolby Atmos for Headphones, the DTS version, and Windows Sonic are all able to do it.

**Comment by ThreeDeeJay** [comment]
@ValZapod @VoidXH Passthrough/bitstreaming is the easier part. The part I'm interested in is actually decoding and spatializing the Atmos track/stream into 3D audio (with height), instead of just playing/virtualizing the 5.1/7.1 track without height or letting an AVR or soundbar handle it, because I don't have any of those 😅

I know apps like Movies & TV can play Dolby Digital+ Atmos and spatialize it using renderers like Sonic/Atmos for Headphones/DTS Headphone:X/etc., but the reason why I'm looking into passthrough particularly is so that I can use other players like Kodi and also so that I can use my own custom HRIR in Cavern by letting it handle the decoding/spatialization.

Or are you guys saying that MPC-HC + LAVfilters *can* use passthrough into Windows spatial sound renderers? 
I couldn't get it working. By default, MPC engages the spatial audio renderers so that Sonic virtualizes the surround output, but the height is lost in the process (the top right gets flattened into front right so it sounds the same)
![mpc-hc_pkpAGHAqmu](https://user-images.githubusercontent.com/71472458/211509180-dd5131e3-f55f-4073-9ee5-331684ea3cba.png)
And if I check DD+ bitstreaming, LAV audio decoder crashes on playback start and the audio becomes panpot stereo (not virtualized anymore)

Kodi's audio engine also crashes when enabling passthrough. not sure if it's because it's expecting a non-existent decoder on the other end or because the device itself doesn't support DD+ bitstreaming.
![image](https://user-images.githubusercontent.com/71472458/211515461-f29e59fd-69dc-4a9e-8395-0169d44dfb73.png)


Is there something I'm missing? 🤔

**Comment by ValZapod** [comment]
>MPC-HC + LAVfilters can use passthrough into Windows spatial sound renderers?

No, only HDMI passtrough.

**Comment by ThreeDeeJay** [comment]
@ValZapod Yeah, but that's not quite what I'm looking for.
On a side note, I heard that Dolby Access comes with a decoder other players can use.
I'm not sure what it adds in addition to Windows' built-in [Dolby Digital+](https://learn.microsoft.com/en-us/windows/win32/medfound/dolby-audio-decoder) Atmos decoding (perhaps TrueHD?).
I'd still prefer to have Cavern do the decoding and spatialization since it's free and allows custom HRTF though.
