### ISSUE TITLE
Channel matching for ADM BWF (Dolby Atmos)

### ISSUE THREAD

**Issue by VoidXH** [VoidXH/Cavern#64]
Only objects should take up the object space, and inputs that are channels should be in the mandatory 7.1.2 bed.

**Comment by VoidXH** [comment]
Hopefully it helps.

**Comment by ValZapod** [comment]
>meaningful error message from the Dolby plugins,

What error? There is no error, everything works perfect with regard to ADM.

**Comment by VoidXH** [comment]
Even DACT can't read some of my content after ADM conversion. One example is the Overwatch demo from the 2016 September Demo Disc.

**Comment by ValZapod** [comment]
>One example is the Overwatch demo from the 2016 September Demo Disc.

What is name of m2ts file so I can download only it?

**Comment by VoidXH** [comment]
No idea, I already compressed and ordered it. I do own the physical disc, but I don't have a reader anymore.

**Comment by ValZapod** [comment]
The largest actually. Called 00032.m2ts. Will test for you in all apps.

**Comment by ValZapod** [comment]
Verified in Dolby Media Encoder, it is all good. Encoded in thd, no problem.

**Comment by VoidXH** [comment]
Then what is DACT's problem?

**Comment by ValZapod** [comment]
What problem?

![image](https://user-images.githubusercontent.com/31514790/212270842-15802476-2c4f-43f2-965c-2a7b1291991c.png)

![image](https://user-images.githubusercontent.com/31514790/212271040-20fc7608-4c4a-40a2-856d-a3b7c02f03e6.png)

![image](https://user-images.githubusercontent.com/31514790/212271217-dc2fdbfe-ccbb-4195-9e61-fed9be7dda0a.png)

**Comment by VoidXH** [comment]
This either didn't work with the last commit or I have a different version. I'll check.

**Comment by VoidXH** [comment]
Looks like mine's different.
![image](https://user-images.githubusercontent.com/7473142/212353706-1f6c7940-c58a-49e3-b845-e48c640d6089.png)

**Comment by ValZapod** [comment]
Are you using 24 bit ADM? Are you using latest version of DACT? see: https://developer.dolby.com/tools-media/utilities/dolby-atmos-conversion-tool

You certaonly are bot using windows 11...

**Comment by ValZapod** [comment]
ADM 24 bit is 1 142 768 287 bytes in size and has md5 EBD7E16FCFE406B42BA9470B6CDB1295. If that is not the case for you I can send you the file.

**Comment by VoidXH** [comment]
For the original, `ffmpeg -i .\Overwatch.mkv -vn -map 0:a:0 -c:a copy -f md5 o.md5` results in `MD5=e2e191eb631844004095d73c4d97c160`.

The MD5 with the latest release in 24-bit mode:
`ffmpeg -i .\Overwatch.wav -c copy -f md5 o.md5` results in `MD5=449259546f6fddd06a4cb8f228a98354`.
`ffmpeg -i .\Overwatch.wav -f md5 o.md5` results in `MD5=707697d26e01e4cd273221ef4bec98ef`.

**Comment by ValZapod** [comment]
>The MD5 with the latest release in 24-bit mode:

That is an incorrect command. -f md5 by default results in 16 bit pcm. You need to specify -c:a pcm_s24le. Also, obviously -c copy will not copy adm metadata, it does not know about it.

I was just talking about file's md5 though i did get 449259546f6fddd06a4cb8f228a98354 and 707697d26e01e4cd273221ef4bec98ef.

**Comment by VoidXH** [comment]
So we have the same output, but it works for you and not for me?

**Comment by ValZapod** [comment]
Did you check the md5 with hashtab? https://www.softportal.com/software-19546-hashtab.html

**Comment by VoidXH** [comment]
Size is 1 142 767 076 and MD5 is `9026432AF3152B51535CC99428C8DC81`, looks like you have more object movement. Does your E-AC-3 track have the same MD5 in FFmpeg (`e2e191eb631844004095d73c4d97c160`)?

**Comment by ValZapod** [comment]
>Does your E-AC-3 track have the same MD5 in FFmpeg

We already checked that PCM bytes are the same with ffmpeg, so the only difference must be iXML. BTW, I use x64 bytecode, while you set everything to 32 bit + 64 bit. Here is iXML: 
[cacawe1.zip](https://github.com/VoidXH/Cavern/files/10419268/cacawe1.zip)


>Does your E-AC-3 track have the same MD5 in FFmpeg (e2e191eb631844004095d73c4d97c160)?

Yes, this is md5 in hastab.

**Comment by VoidXH** [comment]
The results have major differences. A deterministic program should not have these kind of discrepancies, I'll investigate and try to find which of these errors is causing Dolby's reader to fail.
![image](https://user-images.githubusercontent.com/7473142/212522186-0d09487c-a565-4d0b-977c-c8f7b3da7c9a.png)

**Comment by ValZapod** [comment]
This looks like another issue like that: https://github.com/VoidXH/Cavern/issues/28#issuecomment-1336016566 (why cannot I comment there?)

@bluewidy Here is your ADM file from Sol Levante.mkv. https://file.kiwi/fb06d1de#GQNus2hjNWNTPn_RGTKTAw

**Comment by VoidXH** [comment]
> This looks like another issue like that: [#28 (comment)](https://github.com/VoidXH/Cavern/issues/28#issuecomment-1336016566) (why cannot I comment there?)

Yes, all BWF issues come down to this, even #38. I have no idea why can't you comment.

**Comment by VoidXH** [comment]
More checks added to #65.

**Comment by ValZapod** [comment]
>Yes, all BWF issues come down to this, even https://github.com/VoidXH/Cavern/issues/38

It appears that this is an issue with the runtime when it is on windows 10 or when it has no Visual Studio 2022 binaries instead of stand alone .Net Runtime. Why is that -- no idea, but all of this is a rounding issue, maybe some standard library function bug. I suppose you can gdb it, but you need kernel debugger. Now, can you attach the left AXML file? I will try to find whether it has some known to me rounding issues.

**Comment by VoidXH** [comment]
> Now, can you attach the left AXML file?

[Here it is.](https://drive.google.com/file/d/1CT6YMzonDC0sEXRouqItJqEDbgVSO7cg/view?usp=sharing)

**Comment by ValZapod** [comment]
>I will try to find whether it has some known to me rounding issues.

Yep. See first change in BeyondCompare is

            <position coordinate="Z">0.0666666800</position>

vs

**Comment by ValZapod** [comment]
On the other hand I see that:

```
          <audioBlockFormat audioBlockFormatID="AB_00031006_000000c0" rtime="00:03:15.76666" duration="00:00:00.00933">
            <cartesian>1</cartesian>
            <position coordinate="X">1.0000000000</position>
            <position coordinate="Y">-0.9653065000</position>
            <position coordinate="Z">0.0016777050</position>
            <jumpPosition interpolationLength="0.009310">1</jumpPosition>
          </audioBlockFormat>
```

set a breakpoint on newly added code with condition with audioBlockFormatID, and debug why mine has no Z:

```
 <audioBlockFormat audioBlockFormatID="AB_00031006_000000c0" rtime="00:03:15.76933" duration="00:00:00.02000">
            <cartesian>1</cartesian>
            <position coordinate="X">1.0000000000</position>
            <position coordinate="Y">-0.9677419000</position>
            <jumpPosition interpolationLength="0.007980">1</jumpPosition>
          </audioBlockFormat>
```

**Comment by ValZapod** [comment]
I also see something happened with AB_0003100a_00000330. Something wrong.

**Comment by VoidXH** [comment]
Looks fine:
`<audioBlockFormat audioBlockFormatID="AB_0003100a_00000330" rtime="00:03:44.22933" duration="00:00:00.01733">
  <cartesian>1</cartesian>
  <position coordinate="X">0.8917326000</position>
  <position coordinate="Y">0.3329631000</position>
  <position coordinate="Z">0.9333335000</position>
  <jumpPosition interpolationLength="0.017290">1</jumpPosition>
</audioBlockFormat>`

**Comment by ValZapod** [comment]
>It's a snapshot of a different frame, see rtime. Positions by themselves can't be an issue, but alignment could be.

So, Ctrl-F for "position coordinate="X">" and Y and Z shows there are 13935, 13935, 12334 in your file and 13937, 13937, 12335 in my file. So...

**Comment by ValZapod** [comment]
>Looks fine:

Not really.

![image](https://user-images.githubusercontent.com/31514790/212751310-26fa1c17-389f-4042-8af4-adebcaa465fc.png)

**Comment by VoidXH** [comment]
> Not really.

This is just a poor display. You can see manually that all IDs are in order on both sides.

**Comment by ValZapod** [comment]
IDs are in order, but data in them is off-by-two. Data in 332 on the right is inside 334 on the right.

😉

**Comment by VoidXH** [comment]
That's not a compatibility breaking issue, and skipping for still objects is intended.

**Comment by ValZapod** [comment]
So you cannot tell which of two xmls your code intended? 🤔🤔

Can you address the rounding issue with 1/15? You obviously use some .Net standard function to round, right? Well, there was IMHO a bug there in the standard library. Infinite precision arithmetic is hard to get right.

**Comment by VoidXH** [comment]
> So you cannot tell which of two xmls your code intended?

No, I'd have to manually look at the Atmos metadata to confirm. Both sides match the standard completely, this is why this compatibility issue is so strange.

> You obviously use some .Net standard function to round, right?

No, I never use STL for rounding, because it's slow. Rounding is (int)(x + 0.5) anyway.

**Comment by VoidXH** [comment]
This issue is implemented in 82479b4e54254f29b17fc8af404ef7a310747521, did not fix the issue. #65 is next.

**Comment by ValZapod** [comment]
>I never use STL for rounding, because it's slow

But the result is garanteed.

>Rounding is (int)(x + 0.5) anyway.

Oh. You are supposed to remove the . and only add + 500, +50, etc. That is a naive implementation of course, standard library is much more complex. But I know of glibc only, not what .NET Roslyn does. Still a bugbin compiler that does float sum here may be not surprising.

**Comment by ValZapod** [comment]
Well, I tested 82479b4, Dolby Media Encoder still works...

**Comment by VoidXH** [comment]
At least the file sizes are smaller now. Validator still doesn't report timing or positional issues, those are also valid. It must be some other formatting issue.

**Comment by ValZapod** [comment]
Can you try .Net 7.0? In Visual Studio 2022 you need to right click on CavernizeGUI Properties and select .NET 7.0. Also I have 11 January security update for 7.0.2.

**Comment by VoidXH** [comment]
That didn't fix the issue.

**Comment by ValZapod** [comment]
When you remux from ADM wav to ADM wav with DACT it gives all digits in precision of X, Y, Z. Why is that? Also what is up with different values all over???

```
<audioBlockFormat audioBlockFormatID="AB_0003100b_00000a17" rtime="00:02:58.93200" duration="00:00:00.00933">
						<cartesian>1</cartesian>
						<position coordinate="X">0.8709677458</position>
						<position coordinate="Y">0.0574236512</position>
						<position coordinate="Z">0.7926710844</position>
						<jumpPosition interpolationLength="0.009312">1</jumpPosition>
					</audioBlockFormat>
```


vs 

```
          <audioBlockFormat audioBlockFormatID="AB_0003100b_00000a17" rtime="00:02:58.93199" duration="00:00:00.00934">
            <cartesian>1</cartesian>
            <position coordinate="X">0.8709678000</position>
            <position coordinate="Y">0.0574236800</position>
            <position coordinate="Z">0.7926711000</position>
            <jumpPosition interpolationLength="0.009310">1</jumpPosition>
          </audioBlockFormat>
```


>That didn't fix the issue, the resulting file was exactly the same.

You do use Windows 8, right? Certainly not windows 11... So that means it should be windows' bug.

**Comment by VoidXH** [comment]
> You do use Windows 8, right?

10.

**Comment by ValZapod** [comment]
Did you know that simply 

```
--- a/Cavern.Format/Transcoders/AudioDefinitionModelElements/ADMChannelFormat.cs
+++ b/Cavern.Format/Transcoders/AudioDefinitionModelElements/ADMChannelFormat.cs
@@ -202,16 +202,15 @@ namespace Cavern.Format.Transcoders.AudioDefinitionModelElements {
                             cartesian = child.Value[0] == '1';
                             break;
                         case ADMTags.blockPositionTag:
-                            float value = QMath.ParseFloat(child.Value);
                             switch (child.GetAttribute(ADMTags.blockCoordinateAttribute)[0]) {
                                 case 'X':
-                                    x = value;
+                                    x = (float)QMath.ParseFloat(child.Value);
                                     break;
                                 case 'Y':
-                                    z = value;
+                                    z = (float)QMath.ParseFloat(child.Value);
                                     break;
                                 case 'Z':
-                                    y = value;
+                                    y = (float)QMath.ParseFloat(child.Value);
                                     break;
                                 default:
                                     throw new CorruptionException(block.GetAttribute(ADMTags.blockIDAttribute));
```


produces 500 bytes smaller Cavern.Format.dll? And who knows what memory footprint smaller.

Can you try changing the rounding to all digits and maybe try rounding with STL? BTW, how do you do static linking in .NET? So that I can give you STL from my PC. Oogh. Will compiling for newer Windows 11 22H2 SDK allow one to include newer library for it, inside Microsoft.Windows.SDK.NET.dll? What is even inside that Microsoft.Windows.SDK.NET.dll??? Here:

**Comment by VoidXH** [comment]
> produces 500 bytes smaller Cavern.Format.dll?

No, it doesn't. .NET DLLs are always divisible with 512 bytes (they are storage block-aligned), and this just takes off 1 or 2 significant bytes at the border for performance degradation.

> Can you try changing the rounding to all digits and maybe try rounding with STL?

I've checked, and there's no rounding is involved in ADM generation. The only applicable class is ADMTimeSpan, and it also has only atomic FPU operations, which should be in no way changed by the runtime.

**Comment by ValZapod** [comment]
>.NET DLLs are always divisible with 512 bytes (they are storage block-aligned),

When I said 500, I meant 512. Rounded. Sorry :) See screenshot.
