### ISSUE TITLE
Enhance ADM Validator

### ISSUE THREAD

**Issue by VoidXH** [VoidXH/Cavern#65]
More validation points:
* Check if WAVE headers are correctly aligned and no zero tags are present.
* Check if the length of the track matches the used bytes.
* Check if all tags are closed and at the right place.
* Check if it's a Dolby Atmos file (has DBMD), and if so, the 7.1.2 bed and only that bed is present at the correct locations.
* Check presence of mandatory tags/attributes.
* Check if IDs are in order and there are no missing entries.
* Check if sample rates match and the channel assignment is valid.

**Comment by VoidXH** [comment]
Added in 1b458768891d913bf5d4cd3025515cfaeb676aae:
* Check if WAVE headers are correctly aligned and no zero tags are present.
* Check if the length of the track matches the used bytes.
* Check if it's a Dolby Atmos file (has DBMD), and if so, the 7.1.2 bed and only that bed is present at the correct locations.
* Check if IDs are in order and there are no missing entries.

Remains:
* Check if all tags are closed and at the right place.
* Check presence of mandatory tags/attributes.
* Check if sample rates match and the channel assignment is valid.

**Comment by ValZapod** [comment]
This changes nothing herein terms of rounding.

**Comment by VoidXH** [comment]
Why would rounding be an issue? Positions are positions, all values between -1 and 1 are valid. Only timing issues could cause this, and I have no idea what the requirements are.

**Comment by ValZapod** [comment]
>Why would rounding be an issue? Positions are positions, all values between -1 and 1 are valid.

Imagine Dolby put some watermark inside, that causes only specific numbers to work. And your float rounding broke it. Just saying.

**Comment by VoidXH** [comment]
More likely than not the time wrapping is incorrect. I think Dolby needs to wrap to 64 sample blocks, that's worth a test. Bypassing a watermark is not legal anyway.

**Comment by VoidXH** [comment]
The last bytes are part of the object metadata block. While it's structure is unknown and written as zeros by Cavern, its small size rules out watermarking.

**Comment by ValZapod** [comment]
By last two bytes I meant every X, Y, Z, coordinate.

**Comment by VoidXH** [comment]
I just created an ADM file where all positions are zero. It didn't fix the issue, but Cavern still plays it, so it's timing.

**Comment by VoidXH** [comment]
Setting the interpolation lengths to zero fixes the issue. This will be about those.

**Comment by VoidXH** [comment]
Found the reason. Dolby ONLY allows 0 or 250-sample interpolation. No idea why, the standard doesn't have this restriction. Dolby Atmos ADM exports now conform to this, including the newest release. Also, 16 bit works with DACT.

**Comment by ValZapod** [comment]
>Dolby ONLY allows 0 or 250-sample interpolation. No idea why, the standard doesn't have this restriction.

Now all interploationLength are 0.520 but thd that is produced is the same, almost. Okay...

**Comment by VoidXH** [comment]
Yes, and this is correct. Dolby only allows values close to 0.5208.

**Comment by ValZapod** [comment]
Not here.

**Comment by ValZapod** [comment]
> Not here

Are there still rounding and timing differences in newest 120 MB iXML https://github.com/VoidXH/Cavern/files/10450312/00032.track_43537.zip

compared to what your windows 10 produces
?

Cause if there still is you are interpolating between wrong values. I also noticed there are some horrible artefacts in Overwatch in Davinci atmos renderer on MY system. Will investigate further.

Meanwhile it would be nice to know at least whose XML is right per your code.

**Comment by VoidXH** [comment]
> Cause if there still are you are interpolating between wrong values.

Tries turning it off completely and exporting every frame, it still didn't work with some content.

> I also noticed there are some horrible artefacts in Overwatch in Davinci atmos renderer

Yes, the gain is over 0 dB in some cases for that specific content. That's because of the removal of the -6 dB gain. I probably should just add it back with maybe -3 dB.

> Meanwhile it would be nice to know at least whose XML is right per your code.

Not possible unless you manually check all OAMD positions.

**Comment by ValZapod** [comment]
>I probably should just add it back with maybe -3 dB.

Did you see Dolby Media Encoder settings that have those -3 dB? That is the default for Downmixing metadata each for Lt/Rt center, Lt/Rt surround, Lo/Ro center, Lo/Ro surroind. In fact ffmpeg implemented that. See https://patchwork.ffmpeg.org/project/ffmpeg/list/?series=8204

**Comment by ValZapod** [comment]
>Not possible unless you manually check all OAMD positions.

What is the problem with that?? Set a breakpoint in Visual Studio debugger.

**Comment by VoidXH** [comment]
> Did you see Dolby Media Encoder settings that have those -3 dB?

Oh, it's about the 5.1/7.1 downmix? I thought that's about stereo.

> What is the problem with that??

Manually checking <objects> * 3 * 48000 / 64 values every second.

**Comment by ValZapod** [comment]
>Manually checking * 3 * 48000 / 64 values every second.

What is the problem? PC can check billions per core, no problem. You just need to write if on XML id and then step forward with F5.  You know how it is with a debugger.

**Comment by VoidXH** [comment]
That's not really debugging, that's an entirely new code. I was saying there's no quick way of doing this.

**Comment by ValZapod** [comment]
> That's not really debugging, that's an entirely new code. I was saying there's no quick way of doing this.

You may use new code to debug, in fact that is how printf debugging works. 🤣 Advanced debuggers can look up pointer accesses and memory data access and all memory string search and even full history debugging is possible, see https://youtu.be/eGl6kpSajag

As I said you may need kernel debugger though, since this is OS bug, since we have same binaries. VS 2022 must be able to do that though. There are also hylervisor level debuggers and Ring -3 debuggers, like Vtune profiler /Intel GDB inside OpenAPI, they operate on Minix OS inside CPU/chipset.

**Comment by ValZapod** [comment]
>Oh, it's about the 5.1/7.1 downmix? I thought that's about stereo.

Do you want me to encode some test Atmos audio (give me sample you want to encode) with different metadatas (tell what uou need).

**Comment by VoidXH** [comment]
> Do you want me to encode some test Atmos audio (give me sample you want to encode) with different metadatas (tell me what you need).

I just need to know what values should be used for setting channel gains.

**Comment by ValZapod** [comment]
Artefacts in overwatch:

some stuff in 02:20 --> 02:23 (that are timecodes in NDF)

Then 02:30...

Then horrible one on 03:53...

(That is in 7.1.4 mode render in davinci.) Same in binaural.

**Comment by VoidXH** [comment]
That's the clipping issue we've talked about. If there's nothing in the metadata, JOC content will just be attenuated by 3 dB.

**Comment by ValZapod** [comment]
> That's the clipping issue we've talked about. If there's nothing in the metadata, JOC content will just be attenuated by 3 dB.

I did encode some EAC3 content. Please give me time and I will attach different metadata files.

**Comment by ValZapod** [comment]
There are still some small artefacts in 01:47 in overwatch.

**Comment by VoidXH** [comment]
Audio quality is not related to ADM, it's the JOC decoder's fault.
