### ISSUE TITLE
TrueHD Atmos?

### ISSUE THREAD

**Issue by ValZapod** [VoidXH/Cavern#7]
TrueHD Atmos is not public spec and no Huffman tables are public... But you can try the Dolby reference player reverse engineering.

What about applying EAC3 panning meta for TrueHD? Is 1:1 possible?

**Comment by VoidXH** [comment]
Does TrueHD Atmos work the same way, by mixing from a 7.1 stream? In that case, applying the metadata to another track might work, that could be a new feature to select both waveform and metadata tracks separately.

**Comment by ValZapod** [comment]
> Does TrueHD Atmos work the same way, by mixing from a 7.1 stream?

It should, but it is Dolby we are talking about, there is also an issue there is no priming in TrueHD... I do have TrueHD file that should look the same as EAC3: Yello album. [Blu-ray version](https://www.amazon.com/Point-Dolby-Atmos-Yello/dp/B08NVGHFD1/ref=sr_1_2?crid=370U5UQIWZDYV&keywords=Yello&qid=1662386519&sprefix=yello%2Caps%2C204&sr=8-2) is TrueHD, but I also have Atmos EAC3 version from Tidal. Nothing else. You can try applying eac3 metadata on wav from TrueHD... I will send you the files. 

P.S. Actually, no. It does not work (causes crazy artifacts) <Dolby we are talking about>.



Here is a very small TrueHD in mp4 sample: https://user-images.githubusercontent.com/31514790/188469300-9947f92e-31b4-4bf1-9fad-29660747a6c8.mp4

**Comment by ValZapod** [comment]
https://github.com/FFmpeg/FFmpeg/commit/36bf549b2706bd10014556a84a33ed6daf5d5373

This says that 4th actual substream is what encodes Atmos metadata

**Comment by VoidXH** [comment]
I did some testing with Dolby demos, using the TrueHD track from the same file actually works with less artifacts than using the DDP PCM. I'll add a feature to use DDP matrices for TrueHD.

**Comment by ValZapod** [comment]
> with Dolby demos

What demo did you try? Because Yello above has different behaviour for TrueHD! Panning meta I suppose is quite different.

**Comment by sw5163** [comment]
If this can help, [00003.m2ts](https://drive.google.com/drive/folders/1E4Go5zLiR4LlMiT8GQTJxxF22-4q1qTe?usp=sharing) has both TrueHD/atmos and eac3/atmos in it.
I really hope there is a way to software decode TrueHD/atmos and get 16-channel lossless pcm/wav.

**Comment by ValZapod** [comment]
> [00003.m2ts](https://drive.google.com/drive/folders/1E4Go5zLiR4LlMiT8GQTJxxF22-4q1qTe?usp=sharing) has both TrueHD/atmos and eac3/atmos in it.

Interesting, this file from march 2018 demo disk from Dolby reports 17 dynamical objects, which is impossible, also on report it only says 1 bed + actual 15 dyn. objects, which is correct... That is the same bug as in Trinnov then. Will open new bug!

**Comment by VoidXH** [comment]
> What demo did you try?

Dolby Demo Disc 2016 and Dolby UHD Demo Disc 2018.

> reports 17 dynamical objects

I'll look into it.

**Comment by VoidXH** [comment]
17 object reporting was fixed in 816f7c28703605692d13eb9c56ae26a2d30b37a3.

**Comment by sw5163** [comment]
Sorry for being stupid, but is there a tutorial to convert TrueHD/atmos to 16 channel lossless wav/mp4 file by applying eac3/atmos metadata? I really want to give it a try, but I don't know how.

**Comment by VoidXH** [comment]
There is currently no documented way of TrueHD Atmos decoding, this issue will be solved with a lackluster workaround until the documentation becomes available.

**Comment by sw5163** [comment]
Sorry, I thought you can apply eac3 atmos metadata on TrueHD and have 16 channel lossless. My bad.

**Comment by VoidXH** [comment]
That is the workaround that will happen, but you will need both TrueHD and E-AC-3 tracks of the same exact file. Muxing multiple releases of the same content won't work for this, so it will be only for demos.

**Comment by VoidXH** [comment]
Oops, accidentally marked complete.

**Comment by sw5163** [comment]
Many thanks for the explanation!

**Comment by ValZapod** [comment]
> eac3 atmos metadata on TrueHD and have 16 channel lossless

You can! But it may not work for true Atmos sound from Tidal, that does not use AC3 (not EAC3) internally for 4 out of 8 channels. The way it works is you can apply in Cavern driver (not GUI) EAC3 in mkv metadata to TrueHD decoded to wav, but one sample I tested it did not work, causing crazy artifacts.

**Comment by sw5163** [comment]
I found 
http://download.dolby.com/us/en/test-tones/dolby-test-tones_7_1_4.mp4
http://download.dolby.com/us/en/test-tones/dolby-test-tones_9_1_6.mp4
on Dolby's [legacy page](https://web.archive.org/web/20180121102416/https://www.dolby.com/us/en/guide/test-tones.html)
Mediainfo reports they are 6 channel, but Dolby says they are 7.1.4/9.1.6
I can't find disc version of those test files, but I found this on Youtube 
https://www.youtube.com/watch?v=Fsrq0ZS6Qno
(download link under the introduction of video)
http://www.snamsup.com/download/Dolby-Atmos-Demo-Test/DOLBY-ATMOS-Test-Tones-9-1-6.zip
I have no idea what im doing.

But does that mean if the metadata in an eac3/atmos is suppoesed to upmix 6 channel to 9.1.6 lossy,
then we can extract that metadata, applying to 6/8 channel of TrueHD, and get 9.1.6 lossless pcm?

Please forgive me if this sounds really a dummy question

**Comment by ValZapod** [comment]
> Mediainfo reports they are 6 channel

but 11 objects. No, you cannot use 6 channels EAC3 for 8 channels TrueHD.

**Comment by sw5163** [comment]
> No, you cannot use 6 channels EAC3 for 8 channels TrueHD.

Right, make sense. 
Although it sounds really stupid, but what if I just abandon the left and right mid channel of TrueHD?
Will that results in a little inaccurate but playable lossless 9.1.6?

**Comment by VoidXH** [comment]
No, objects are mixed from all 8 input channels. These demos are available with a DD+ 7.1 base on most Dolby demo discs by the way.

**Comment by sw5163** [comment]
So they actually can upmix 6 channels to 9.1.6 with atmos metadata?
I always thought atmos is only there for the sky channels.
Thank you guys, Looks like I still have a lot to learn.

**Comment by ValZapod** [comment]
No, Atmos dyn. objects can be anywhere, e.g. John Williams' album has all
sound in between actual 9.1.6 channels.

**Comment by VoidXH** [comment]
TrueHD track is now used with E-AC-3 metadata when available in the same file: 24e1b7ff0bcde5b2844ad16b52906771c307aef2.

**Comment by sw5163** [comment]
This is a great work!
Many thanks for the efforts!

**Comment by ValZapod** [comment]
> No, Atmos dyn. objects can be anywhere, e.g. John Williams' album has all sound in between actual 9.1.6 channels.

Which means most objects render on multiple speakers of 9.1.6. this is how it looks like on that Star wars soundtrack (in fact even in 22.2 with God's voice this is still between): 

![image](https://user-images.githubusercontent.com/31514790/190606801-fd9abeca-ca1a-43d7-a722-11eb61943db9.png)


![image](https://user-images.githubusercontent.com/31514790/190606827-49e89359-0040-4fc1-a78f-f37b7d0b961f.png)

**Comment by ValZapod** [comment]
> EAC3: Yello album. Blu-ray version is TrueHD,

BTW, this obviously will never work becasue Tidal has 6 channels, while TrueHD 8 channels. So more space in TrueHD.

**Comment by ValZapod** [comment]
Why is your 0.wav file created grom TrueHD 16 bit only? For TrueHD it is always wrong.

**Comment by ValZapod** [comment]
I tried older versions. There is not TrueHD decoder anymore?

**Comment by VoidXH** [comment]
No, that part was removed when the E-AC-3 decoder was finished.

**Comment by bluewidy** [comment]
This topic is of great interest to me! Hey is there a way to extract only the atmos metadata from a TrueHD Atmos track and then insert it into the EAC3? So my goal is to convert EAC3 tracks to EAC3-JOC.

The reason I want this is because the current local media player that can decode the object and pass the object to Dolby Atmos for Headphones is Microsoft's media player, which doesn't support TrueHD Atmos, but instead supports EAC3-JOC.

**Comment by VoidXH** [comment]
> Microsoft's media players can read the object and pass it to the Dolby Atmos for Headphones renderer

Yes, but developers can choose to completely use Microsoft's pipeline or nothing from it at all. This data is inaccessible.

**Comment by bluewidy** [comment]
> is there a way to extract only the atmos metadata from a TrueHD Atmos track and then insert it into the EAC3?

Ah... the reason you have avoided answering this question is because of uncertainty?

**Comment by VoidXH** [comment]
> Ah... the reason you have avoided answering this question is because of uncertainty?

We don't even know what's in the TrueHD metadata, it's just gibberish to the E-AC-3 parser. E-AC-3 is optimized for a small size, while TrueHD isn't. It has a format favoring precision, unlike E-AC-3, which, for example, only has 32 object positions on each axis.

**Comment by ValZapod** [comment]
>probably has a format favoring precision, unlike E-AC-3, which, for example, only has 32 object positions on each axis.

Why would it? They bpth use spatial encoding.

**Comment by VoidXH** [comment]
> Why would it? They both use spatial encoding.

Yeah, but 5 bits are a bit slim for a position.

**Comment by bluewidy** [comment]
> Did not we agree on that you can use panning metadata from EAC3 on TRUEHD base layer decoded to wav?

That's why I asked the question too. Because I thought the reverse would also be possible.

**Comment by ValZapod** [comment]
>Because I thought the reverse would also be possible.

EAC3 is open standard, TrueHD is not, in Atmos part.

**Comment by bluewidy** [comment]
https://github.com/DolbyLaboratories/dbmd-atmos-parser

Does that mean this tool only supports EAC3-JOC? Isn't this what you're using for the Atmos reverse engineering?

**Comment by ValZapod** [comment]
No that is for WAV container.

**Comment by bluewidy** [comment]
I think... I don't think it's my place anymore. I can't understand what you're saying because of the gap in knowledge. I'll just be the cheerleader cheering the developers on :)

**Comment by bluewidy** [comment]
@VoidXH Sir, I found something!!
https://gist.github.com/Plazik/e950267cc580bcde371ea7879aaa3d5d
(source : https://wedframe.ru/archive/index.php?t-6541.html)

**Comment by VoidXH** [comment]
That's using Dolby Reference Player, it's not an actual decoder.
