### ISSUE TITLE
Persistent 24-bit WAV bit depth for Cavernize

### ISSUE THREAD

**Issue by VoidXH** [VoidXH/Cavern#71]

**Comment by ValZapod** [comment]
There is also one argument that  I use only 24 bit personally, of course, and every time I have to press on the flag.

>As far as I know most ADM users use it for JOC playback on studio systems.

My system supports 16, 24 and even 20 bit, even though nvidia does not even support 20 bit PCM and neither does ffmpeg, just saying.   

![image](https://user-images.githubusercontent.com/31514790/215086057-28fd65d3-0cc6-42aa-b096-14033d5b5852.png)

**Comment by VoidXH** [comment]
> There is also one argument that I use only 24 bit personally

That's not needed for system output at all. An average room's background noise is 40 dB SPL, which means you have to listen over 136 dB (which is 4x louder than instant hearing loss) for 24 bit to have any effect. This is also another reason why I default to 16.

**Comment by VoidXH** [comment]
Done in 3929a0843b6e3ac25cac7f420a9d754fa2e4ffb0.

**Comment by ValZapod** [comment]
>An average room's background noise is 40 dB SPL, which means you have to listen over 136 dB (which is 4x louder than instant hearing loss) for 24 bit to have any effect.

Yes? Why this exists then? 24BIT/352.8kHz?
https://web.archive.org/web/20200224092812/https://www.2l.no/hires/

**Comment by VoidXH** [comment]
> Why this exists then?

For bragging rights basically.

**Comment by ValZapod** [comment]
So, you added setting inside user.config and the very initial default is on (24 bit)? Nice. BTW, this breaks bissecting.
