### ISSUE TITLE
ASIO or WASAPI Output

### ISSUE THREAD

**Issue by hockinsk** [VoidXH/Cavern#72]
Is there any way output can be configured to ASIO or WASAPI? I'm struggling to play anything without what sounds like a buffer overloading issue. ie slow glitch playback.

**Comment by VoidXH** [comment]
Sadly that's a buffer issue. Make sure you play back from an SSD in the Cavern driver, or convert the content with Cavernize.

**Comment by hockinsk** [comment]
OK thanks. The files are on an the SSD main drive of the OS, but I guess the onboard windows audio is struggling because there's very high CPU load with Cavern playback. I guess either I need more powerful computer or the onboard Realtek audio isn't capable of the buffer size require.

**Comment by VoidXH** [comment]
The system audio buffer is not the issue, E-AC-3 JOC is just very heavy on the CPU and Unity can't use the same optimizations Cavernize can.

**Comment by hockinsk** [comment]
I see, nit problem I will run it on my studio workstation which has a faster CPU than my i7 laptop. Kind regards.

**Comment by VoidXH** [comment]
Please download the version just released. It has major performance improvements in both Cavern Driver playback and Cavernize conversions.

**Comment by hockinsk** [comment]
Wow, thank you Bence, that's a huge improvement. Brilliant!

**Comment by ValZapod** [comment]
Yep, 10x speed on overwatch is nice.

**Comment by VoidXH** [comment]
> The sound has differences though.

Yes, there were a few object movement changes.
