### ISSUE TITLE
Suggestion: Smoothed Object Movements?

### ISSUE THREAD

**Issue by hockinsk** [VoidXH/Cavern#73]
Loving the product, especially seeing the Atmos objects and any animations. As some object movement is very quick, I wonder if it would be possible to add a smoothed trail to the objects? e.g. like a mouse pointer trail? I'm not sure how the 16 spatial groups and object movement is decoded by Cavern though, is it reading the object coordinates or is it a calculation from the channel audio?
![image](https://user-images.githubusercontent.com/1609513/215272746-5474189a-9b3e-40f2-8a09-fccee61ffc9e.png)

**Comment by VoidXH** [comment]
I really like this idea, I'll just add this to the currently WIP visualizer overhaul. 

> is it reading the object coordinates

Yes, it's entirely from the file, nothing is generated.

**Comment by hockinsk** [comment]
Brilliant, looking forward to it already ; )

**Comment by VoidXH** [comment]
Done in 6a3964928cb1930f2e424d30496085ec3322d3cd and released.

**Comment by hockinsk** [comment]
I feel like you've spoilt me : ) Many thanks, keep up the great work with this very useful tool.
