### ISSUE TITLE
Cavern Driver redesign

### ISSUE THREAD

**Issue by VoidXH** [VoidXH/Cavern#76]
Just show 3 large buttons at the start: channel setup, visualizer, and QuickEQ. These can be different scenes in Unity. QuickEQ should have an easy and an expert mode. Easy shall only have microphone selection/calibration file import, (re)measurement, and result display with a target curve selection when available. Expert is what's currently there.

**Comment by VoidXH** [comment]
There should be a warning before measurements that the Equalizer APO configuration file on the PC is not empty. Offer an option to clear it.

**Comment by AVX22** [comment]
Hi,
Idk if this Cavern Core functionality already exists, but
1- a play, pause ,fastforward button instead of a seek slider would be great!!
2- Default volume should be 50%, i always get deaf loading the files :p

**Comment by VoidXH** [comment]
UI reordered and released with a new launch screen, play/pause/stop buttons were added to the player. Fast forward is not trivial and not really needed for a demo player. Default volume is now -6 dB.
