### ISSUE TITLE
Add back the ability to read the base layer using xxxx0.wav file

### ISSUE THREAD

**Issue by ValZapod** [VoidXH/Cavern#78]
Can you at least add back the ability to read the base layer using 0.wav file? Please? So the algorithm is as follows: if CavernizeGUI sees filename0.wav in the ~\ folder it uses that audio instead of EAC3 decode base layer, but applies eac3 metadata. It was very nice before.

That way you can decode THD by hand and use that as base layer, lossless.

Or you can add an option to use base layer in GUI (select custom base layer to use with eac3 metadata)...

**Comment by ValZapod** [comment]
>I'll add a command-line parameter for it as it's a super rare use case.

It will allow you not to add back ffmpeg at all! I will just decode THD myself and add 256 samples myself too in the very start.

**Comment by VoidXH** [comment]
Use --override-bed <file name> available from 99ff6828fc877a89eea16b4dfc4c454d37c77fba. Requires the main input to be a .ac3/.ec3 file, the ovveride could be any supported format.

**Comment by bluewidy** [comment]
By the way... what is this? What are the benefits of this feature and when and how can I take advantage of this feature?

**Comment by VoidXH** [comment]
You can use the TrueHD track for Dolby demos, but nothing else (requires channel count to match).

**Comment by bluewidy** [comment]
Then this feature doesn't seem worth it to me...

**Comment by VoidXH** [comment]
That's why it's hidden.

**Comment by ValZapod** [comment]
>Sample rate of the overriding stream don't match the source stream

Should be "Length of the overriding"...

**Comment by VoidXH** [comment]
Both have to match.

**Comment by VoidXH** [comment]
Done

**Comment by ValZapod** [comment]
Nice fix. So, I am going to play with TrueHD a little bit. I think you mentioned here that TrueHD metadata may be higher quality? Interesting, how do you know that? Maybe Huffman tables are just that good in EAC3? Also 5 bit is why X, Y, Z are not full precision?

https://www.audiosciencereview.com/forum/index.php?threads/atmos-finally-decoded-in-pc-mac.32351/post-1420126

**Comment by VoidXH** [comment]
> Interesting, how do you know that?

The answer is at the same topic. The size of the unknown Atmos metadata blocks can surpass 1 Mbit/s, which is more than the entire DD+ stream.

> Maybe Huffman tables are just that good in EAC3?

That wouldn't help, we're talking about a tenfold size difference.

> Also 5 bit is why X, Y, Z are not full precision?

Yes, that's not that much, not even comparable to the master. It doesn't really matter though, because it can be encoded as such that it's not audible. I personally wouldn't really care if all mixes were channel-based, that was the idea behind the current LAF.
