### ISSUE TITLE
FFmpeg does not force -c:a pcm_s24le for wav (*0.wav), EAC3 is >16 bit technically

### ISSUE THREAD

**Issue by ValZapod** [VoidXH/Cavern#8]
It may not be an obvious problem for eac3, but that is a problem for truehd (talking as ffmpeg dev, that read a lot of mlpdec/enc.c code). TrueHD is not like MLP: it does not have metadata that signals whether it is 24 bit or 16 bit. When you go from TrueHD to flac you will get 24 bit mode, not 16 bit, never 16 bit, same for eac3. TrueHD can actually be just 16 bit (on all frames or only on some) and then that 24 bit flac will be bitperfect with wav 16 bit default upconverted to 24 bit. **But usually it is not, cause that is cheating by Hollywood.** That is never done, because you need to decode to get whether it is 16 bit or not, so it is just always 24 bit, **and wav 16 bit default is more like a bug.**

You can create 01 - Yello - Waba Duba0.wav (that will be deleted after ADM is created by CavernizeGUI.exe) with ffmpeg.exe -i "01 - Yello - Waba Duba.ac3" -c:a pcm_s24le "01 - Yello - Waba Duba0.wav"
v

Then create 16 bit: ffmpeg.exe -i "01 - Yello - Waba Duba.ac3"  "01 - Yello - Waba Duba1.wav"

Then upscale 16 bit to 24 ffmpeg.exe -i "01 - Yello - Waba Duba.ac3" -c:a pcm_s24le  "01 - Yello - Waba Duba3.wav" and 

compare the two. They will be very different! Why? Because EAC3 is done that way, lossy codecs can be more accurately approximated by more bits, like here.

I provided a warkaround (creating 24 bit 01 - Yello - Waba Duba0.wav), but that is hack. I think you need to fix it in ffmpeg script.

What does ETSI spec says about it? I can imagine it should force 24 bit.

**Comment by VoidXH** [comment]
24 bit will be forced for all intermediate files.

**Comment by ValZapod** [comment]
> both for FFmpeg

Not for ffmpeg. I can see when you create ADM (for what was called raw objects before) original ffmpeg wav (not 16 track object ADM) is 16 bit. You need to be fast to see that because after render it will delete it.  My workaround produces different file from 24 bit original file.

**Comment by VoidXH** [comment]
Yes, that file will also be 24 bit with -c:a pcm_s24le.

**Comment by ValZapod** [comment]
I recked everything again: you are wrong! 

Mediainfo of 0.wav file 

```
Format                      : Wave
File size                   : 233 MiB
Duration                    : 5 min 18 s
Overall bit rate mode       : Constant
Overall bit rate            : 6 144 kb/s
Writing application         : Lavf59.30.100

Audio
Format                      : PCM
Format settings             : Little / Signed
Codec ID                    : 00000001-0000-0010-8000-00AA00389B71
Duration                    : 5 min 18 s
Bit rate mode               : Constant
Bit rate                    : 6 144 kb/s
Channel(s)                  : 8 channels
Channel layout              : L R C LFE Lb Rb Ls Rs
Sampling rate               : 48.0 kHz
Bit depth                   : 16 bits
Stream size                 : 233 MiB (100%)
```


And moreover here is a screenshot of my ffmpeg that opens when you produce ADM with iXML or separate XML:

![image](https://user-images.githubusercontent.com/31514790/188451568-b945221b-e323-4d59-a074-749eca35bd2f.png)

**Comment by VoidXH** [comment]
I mean, it will be after the fix, not currently :D I'll fix it later tomorrow.

**Comment by ValZapod** [comment]
Thr other absolutely wrong thing that I totally forgot about is that you do not force -drc_scale 0. Thag is wrong.

**Comment by VoidXH** [comment]
Okay, I will also add that one.

**Comment by VoidXH** [comment]
Fixed in ec56bee1f54a6a53e5659da834863a9ff769da62.

**Comment by ValZapod** [comment]
Strange, but it still selects 16 bit, I even deleted the repo fully and recompiled and file is still 16 bit:

![image](https://user-images.githubusercontent.com/31514790/189543402-b174cb6a-a38a-414f-b0d1-883db9e7e3ca.png)

**Comment by VoidXH** [comment]
Found the issue: ADM has a different FFmpeg script than all the other targets. Only the latter was modified, I'll change the other.

**Comment by VoidXH** [comment]
Fixed in 6317705909607eb0e0f670f8ed35b4688d93b4a6.

**Comment by VoidXH** [comment]
There is no FFmpeg decoding anymore, which initial pass do you mean?

**Comment by ValZapod** [comment]
>anymore, which initial pass do you mean?

That email comment was from 5 September. Github only now processed it.
