### ISSUE TITLE
Muxing

### ISSUE THREAD

**Issue by VoidXH** [VoidXH/Cavern#80]
Allow exporting from Cavernize instantly into containers. Just copy the video track and add the supported encoded audio (PCM currently). Support MP4/MOV first because of its simplicity and performance issues with MKV's PCM track seeking on some players.

**Comment by bluewidy** [comment]
> Just copy the video track

Are you planning to make the video tracks copyable even if they are in Dolby Vision or HDR10+?

**Comment by VoidXH** [comment]
I don't know if it will work or not.

**Comment by bluewidy** [comment]
Yes Sir.

**Comment by VoidXH** [comment]
Split into #105, #106, and #107 as basics are done.
