### ISSUE TITLE
Demo Grader

### ISSUE THREAD

**Issue by VoidXH** [VoidXH/Cavern#82]
Add to CavernSamples: a software that goes through an audio track and rates the following metrics:
* Short-term dynamic range
* Long-term dynamic range
* Ground surround usage
* Height surround usage
* Crossover subwoofer use (with emphasis on lower frequencies)
* LFE use (with emphasis on lower frequencies)
* Slam power (LFEs are shorter impulses at larger relative amplitudes)

F, E, D, C, B, A, and A+ ratings should be given by the number of minimum thresholds (set by other demo content) passed in the listed categories.

**Comment by VoidXH** [comment]
Should be just a Cavernize feature (part of report generation, but only when not writing a file), not a separate tool.

**Comment by VoidXH** [comment]
Basics done in 50b7107ea14f66b83d61a4efc727f0e6e369ca71, LFE and toggle for using RenderStatsEx instead of RenderStats are missing. Grading limits should be calculated on some demos.

**Comment by VoidXH** [comment]
Surround usage calculation is also missing.

**Comment by VoidXH** [comment]
Done in 6697909b2ee4355dc81626919fb60eeb76790052.

**Comment by junh1024** [comment]
If you're grading Dolby Demos (where they put a lot of effort into panning different sounds discretely) your tool should mostly work.

If you're grading real-world content, they use upmixing a lot of time, so your tool as effectively a activity monitor (for surround & height), would reward upmixing, which is a bad thing IMO.

Example: Star Trek 2009 5.1.2

![](https://cdn.discordapp.com/attachments/757082238327193722/1094915548082618368/screenshot.1916.png)

Star Trek 2009 seems to have "reasonable" height activity, but it's mainly music upscaled to the height, discrete height SFX is very occasional.

There is also a separate issue where too much surround/height content would sound uncomfortable on real speakers.

**Comment by VoidXH** [comment]
The limits should have been set to reward excess Atmos usage. For example, the No Time to Die demo, which was used everywhere at ISE, and has music mixed to Atmos, still received an F grade.
