### ISSUE TITLE
Translation support

### ISSUE THREAD

**Issue by VoidXH** [VoidXH/Cavern#84]
Add additional languages.

**Comment by VoidXH** [comment]
Possibility for translations along with the Hungarian language added in b44f12ad566991575283ffdca9fe9bb49958fea2.

**Comment by VoidXH** [comment]
Woops, track info and format names are hardcoded and have to be moved to resource files. The track info can be redesigned to a table while I'm on this.

**Comment by bluewidy** [comment]
wow... that's an interesting feature.  Are you planning to embed Google Translate?

**Comment by VoidXH** [comment]
No, that technology is not there yet, and it's even worse for technical text. It's hand-made translation only.

**Comment by bluewidy** [comment]
> It's hand-made translation

whose hand? your hands? or the user's hand?

**Comment by VoidXH** [comment]
It's an open-source project, anyone's work is welcome.

**Comment by VoidXH** [comment]
Complete translation backend in 13a61b18108667c72f84ff7622eb450951fcc076.
