### ISSUE TITLE
COM export for decoders

### ISSUE THREAD

**Issue by VoidXH** [VoidXH/Cavern#85]
This is required for using Cavern's decoders in real-time. After that, it would be as easy as passing a block to Cavern from a barebone DirectShow filter. Add install/uninstall bats (regasm for Cavern and Cavern.Filters with TLB creation), maybe do the same from Cavernize, while also adding CavernAmp to the mix.

**Comment by bluewidy** [comment]
![998498e43bc2d78d6a553e4b55c225b7_w200](https://user-images.githubusercontent.com/40682277/218908948-a46db46d-d3aa-4486-9b16-dcafc7fa7d8c.gif)

**Comment by kaedewang** [comment]
good news. Is it possible to be used except win in the future?

**Comment by VoidXH** [comment]
It's not planned, but once the filter interface is done, it's very easy to port.

**Comment by VoidXH** [comment]
CLR hosting will be used instead.
