### ISSUE TITLE
Object-based LAF reader

### ISSUE THREAD

**Issue by VoidXH** [VoidXH/Cavern#87]
LAF should be split up to a decoder and renderer, with support for the new standard that supports objects.

**Comment by AVX22** [comment]
Hi, what is LAF? What will be its purpose?

**Comment by VoidXH** [comment]
It's Cavern's audio format. Now object-based and lossless, being up to 90% more efficient than ADM BWF, the easiest format on the CPU ever made, even faster than WAV, or equal in the worst case. Perfect for archival of massively multitrack formats like ADM, IAB, or even TrueHD, if that could be decoded (LAF generally takes up 75% space for program audio compared to decoded Atmos tracks).

**Comment by AVX22** [comment]
> It's Cavern's audio format. Now object-based and lossless, being up to 90% more efficient than ADM BWF, the easiest format on the CPU ever made, even faster than WAV, or equal in the worst case. Perfect for archival of massively multitrack formats like ADM, IAB, or even TrueHD, if that could be decoded (LAF generally takes up 75% space for program audio compared to decoded Atmos tracks).

Wow, congrats on this. 
Do you think there will be a workaround for decoding TrueHD Atmos objects even though there is not proper documentation?

**Comment by VoidXH** [comment]
> Do you think there will be a workaround for decoding TrueHD Atmos objects even though there is not proper documentation?

The codec is too complicated for reverse engineering. Dolby even works with bits instead of bytes in all their formats. Some files (like WAV) could easily be decoded just by looking at the file, but for TrueHD, you can't even get the sample rate this way.

**Comment by AVX22** [comment]
Hi, sorry to bump this.
I still get some distortion, normally in isolated effects on some ADM Wav objects.

**Comment by VoidXH** [comment]
That is normal. JOC can only work on 10 bands, and if the sound is not perfectly between band borders, artifacting will remain. Keep in mind that the entire JOC information is only a few kbps.

**Comment by AVX22** [comment]
> That is normal. JOC can only work on 10 bands, and if the sound is not perfectly between band borders, artifacting will remain. Keep in mind that the entire JOC information is only a few kbps.

Good to know! Thanks for the technical explanation :)
