### ISSUE TITLE
QuickEQ Mascot

### ISSUE THREAD

**Issue by VoidXH** [VoidXH/Cavern#89]
This is Melody, and she will help QuickEQ users find ways to improve their audio setup by interpreting measurements, showing what to look for, what the issues are, and what can be done to them.

![DALL·E 2023-02-17 19 56 02](https://user-images.githubusercontent.com/7473142/219760635-879ff69c-8fc2-4dcf-b9b9-ac3e8b23b633.jpg)

**Comment by bluewidy** [comment]
Mascot... yeah this brings back memories in me. I remember the dog mascot that existed in windows xp :)

**Comment by VoidXH** [comment]
That was the inspiration :)

**Comment by VoidXH** [comment]
Done and released.
