### ISSUE TITLE
Site: Option to use stripe for donations

### ISSUE THREAD

**Issue by junh1024** [VoidXH/Cavern#90]
You could use stripe for donations. There's 2 OOTB solutions:

- ko-fi + stripe
- donorbox + stripe

stripe doesn't need to collect too many details for donations, and may have a smaller fee than the current paypal

**Comment by VoidXH** [comment]
Stripe's ToS is not really individual-friendly, but PayPal can be used without logging in. I only receive the name and e-mail of registered donors, which I immediately discard. Currently I can fund every current and upcoming feature or device, so no progress depends on donors. If the donations remain the same (averaging $1/day), it's perfectly enough to cover experimenting with FPGAs and stuff like these. I don't want to live off of donor money, so I don't think it will stay after the hardware is developed.
