### ISSUE TITLE
Respect encoder delay in Matroska

### ISSUE THREAD

**Issue by VoidXH** [VoidXH/Cavern#93]
MKV audio tracks have a CodecDelay field, which might contain the optional E-AC-3 priming that's rarely present in content. This will fix audio sync in these cases.

**Comment by VoidXH** [comment]
@ValZapod, may I ask for your help here? For Edge of Tomorrow, FFmpeg actually has extra silence (about 4500 samples of it) prepending the audio. Where is this coming from?
![image](https://user-images.githubusercontent.com/7473142/222979684-37556b57-9066-4655-b1c7-682b7a88377c.png)

**Comment by ValZapod** [comment]
The whole thing was added only very recently. https://git.videolan.org/?p=ffmpeg.git;a=commitdiff;h=eb325324aabe6ae479bbf15256321da8e39238d4

Are yoy saing there is just one channel being wrong? Just -c copy to file.eac3 and only then extract audio.

4500 samples is too much fir encoder delay.

**Comment by VoidXH** [comment]
The entire track is delayed by about 3 AC-3 frames. This is an E-AC-3 + JOC track. Making a copy to an E-AC-3 track only removed the 1536 samples of priming, but 3000 samples of silence of unknown origin still remains.

**Comment by ValZapod** [comment]
>by about 3 AC-3 frames.

Yes, EAE.EXE USES 768 samples as priming. https://trac.ffmpeg.org/ticket/9471#comment:6

>but 3000 samples of silence of unknown origin still remains.

You do understand that there may be delay relative to video, that has nothing to do with lossy bitsream limitations like priming? There may be an editlist (or equvivalent for mkv) for video too.

**Comment by VoidXH** [comment]
> Yes, EAE.EXE USES 768 samples as priming.

I was talking about 3 frames (4608 samples), not just 3 blocks (768 samples). That's not relevant here. When Matroska has no additional codec delay, the default priming of 1536 samples is used. That is also the case here, as the 4608 samples of delay was reduced to 3072 after a track copy, but this silence is still present.

> There may be an editlist (or equivalent for mkv) for video too.

Why is it present in the audio after extracting it? This silence even had to be encoded into the track, does FFmpeg do this if you export the audio of a track with video delay, with -c copy?

> Removed? You mean added back into decoded sound.

No, removed. There was 3 frames of delay, now it's only 2.

**Comment by ValZapod** [comment]
>Why is it present in the audio after extracting it?

That is a design choice. When playing a video where video plays before any of audio you would have to insert silence, because initialising audio later may be a bad idea. Not that windows 11 dies bot allowed to init or preinit stuff or ALSA for that matter.

>I was talking about 3 frames (4608 samples)

EAC3 frame is 256 samples. 4608 samples is 18 frames.

>only removed the 1536 samples of priming,

You cannot call that priming. Priming is always present in EAC3 or AAC and thus when extracted from container it adds samples, not removes them. Always. Whatever that is, it is not priming aka encoder delay. You can see delay relative to video by looking into first frame of video timestamp and first frame of audio. E.g. in Apple TV all video starts at 10 seconds 0 milliseconds, while audio always starts before that, so priming and other delays are removed THAT way.

**Comment by VoidXH** [comment]
It really looks like a video delay, that track is way longer, thanks.
```
  Stream #0:0: Video: hevc (Main 10), yuv420p10le(tv, bt2020nc/bt2020/smpte2084), 3840x1600 [SAR 1:1 DAR 12:5], 23.98 fps, 23.98 tbr, 1k tbn (default)
    Metadata:
      BPS             : 8018868
      DURATION        : 01:53:27.801000000
      NUMBER_OF_FRAMES: 163224
      NUMBER_OF_BYTES : 6823857865
      _STATISTICS_WRITING_APP: mkvmerge v70.0.0 ('Caught A Lite Sneeze') 64-bit
      _STATISTICS_WRITING_DATE_UTC: 2022-09-05 20:42:02
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:1(eng): Audio: eac3, 48000 Hz, 5.1(side), fltp, 576 kb/s (default)
    Metadata:
      title           : English DDP Atmos 5.1
      BPS             : 576000
      DURATION        : 01:53:26.720000000
      NUMBER_OF_FRAMES: 212710
      NUMBER_OF_BYTES : 490083840
      _STATISTICS_WRITING_APP: mkvmerge v70.0.0 ('Caught A Lite Sneeze') 64-bit
      _STATISTICS_WRITING_DATE_UTC: 2022-09-05 20:42:02
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
```

> EAC3 frame is 256 samples.

That's a block. Dolby and FFmpeg both call the 6-block sized superblock a frame. This is the same in the specification.

**Comment by ValZapod** [comment]
The way you see that is with ffprobe -show_frames (you can select streams, only video, only audio, etc). It allows to see best effort timestamp for frames, look into 10 first video frames, since there may be reordering, DTS (decoding in Annex B) is not the same as PTS (presentation).

**Comment by ValZapod** [comment]
>MKV audio tracks have a CodecDelay field, which might contain the optional E-AC-3 priming that's rarely present in content

Encoder delay aka priming is always present at the start of eac3 audio, and most of the cases in the end. It is not "optional", many just forgot about it while writing libraries and there is no way to signak it in .eac3 files.

Same for AAC. Or even mp3, no problems in mp3, everyone agreed how to signal it in LAME and decoders.

**Comment by ValZapod** [comment]
I was wrong about mp3. Apparently -c copy and LAME encoder in ffmpeg break remainder in some rare cases. ./lame encoder not affected. WTF. 

https://trac.ffmpeg.org/ticket/9755#comment:7

**Comment by VoidXH** [comment]
@ValZapod For all content I could find, PTS = DTS = 0, timestamps started at 0. Checking the EBML, this is correct, the frames had no offset. What EBML entry should I check for time alignment, where else could this extra 3000 samples of silence come from?

**Comment by ValZapod** [comment]
>all content I could find, PTS = DTS = 0, timestamps started at 0

Yeah, they just do not care, even Dolby, on Apple follows the standard. FFmpeg EAC3 encoder in TS will not have any cut. Only mp4 will. Even then it is rather buggy: https://trac.ffmpeg.org/ticket/9471

>Edge of Tomorrow

Is that from a Blu-ray? Cause MakeMKV and Blu-ray spec can have all kind of strange hacks. You can confim if EAC3 ends after the video ends and not in a small way.

Maybe the pirates did a mistake. My exprience with the scene is that they are not very organized. Also, if it is seamless branching Blu-ray EAC3 needs to be truncated in the borders of segments, just as THD.

**Comment by VoidXH** [comment]
This isn't just affecting that movie. While many are fine, Cocaine Bear for example has 512 samples of added delay instead of 3072. If there's no other way to offset a file, I might just have to close this issue and just work on the muxer.
