### ISSUE TITLE
Add 4.1.1

### ISSUE THREAD

**Issue by VoidXH** [VoidXH/Cavern#94]
A spatial layout for users who only have 5.1: LCR + RC + GV.

**Comment by VoidXH** [comment]
Added in c78b3b0c834e75c2977da3d69e65dd8fbaababb7.

**Comment by junh1024** [comment]
Just curious, did anyone specifically request this?

Also, What speaker layout do you have?

**Comment by VoidXH** [comment]
> Just curious, did anyone specifically request this?

I don't remember where the idea came from, but it came up when talking to a 5.1 user.

> Also, What speaker layout do you have?

**Comment by VoidXH** [comment]
Accidentally reopened.
