### ISSUE TITLE
Short blips in file outputs

### ISSUE THREAD

**Issue by fripppp** [VoidXH/Cavern#95]
It always shows up to some extent in all channels except LFE. It seems to be some burst of data causing it, but I don't know if that would be in decoding, rendering, or writing the file.

Attached is a track I downloaded from Dolby Lab's Testing album "DCS Functional Testings" (so I think I'm good to share it) which replicates the problem when played back at around 16.18 seconds in, and a screenshot of the waveform. It seems like some sort of data burst. On other tracks, it can show up multiple times throughout. I'm using the latest pre-release DLLs.

![image](https://user-images.githubusercontent.com/70381552/224842832-69ade71a-2ce8-435b-b033-873e1f482f84.png)

https://drive.google.com/drive/folders/1farrzU1cQybqaBfx0udyqvXQjXNNDupj?usp=sharing

**Comment by VoidXH** [comment]
This is the same as #17. Dolby has to fix the standard documentation for this to work.

**Comment by ValZapod** [comment]
Did you extract it from apple music?!

https://music.apple.com/us/artist/dolby-labs/1599222290

Can we get all album? My email is on my github home page.

**Comment by ValZapod** [comment]
> This is the same as #17. Dolby has to fix the standard documentation for this to work.

Cab you write a wqrning fikter in Cavern GUI that standard is violate here?

**Comment by VoidXH** [comment]
> Can you write a warning filter in Cavernize GUI that standard is violated here?

Since it's not in every frame, I could only add it to the post-render report. There's also the option to silence these parts.

**Comment by ValZapod** [comment]
>I could only add it to the post-render report.

Okay.

>There's also the option to silence these parts.

Also okay, maybe that is how it was designed? :) We need to fix DRC in DRP script and make it work with WAV 24 bit int, not float and then we can try reversing it.

**Comment by VoidXH** [comment]
Sparse JOC is now muted, and an error message is shown that this is expected.
